### PR TITLE
[REF] Manufacturing: reporting restructure

### PR DESCRIPTION
**Pull request by hojo-odoo**
This PR restructures the Manufacturing scope by moving all reporting docs to a new "Reporting" folder.

### CODE REVIEW

**Comment by hojo-odoo** [comment]
Hey @ksc-odoo,

This PR is ready for the first round of review.

Thanks,
John

**Review by ksc-odoo — APPROVED** [review]
hey @hojo-odoo -- Just finished my Peer Review of this PR. Nice work. Once you implement the necessary changes, feel free to move this to the next round. Thanks!

**Comment by hojo-odoo** [comment]
Hey @StraubCreative,

This PR is ready for the second round of review.

Thanks,
John

**Review by StraubCreative — APPROVED** [review]
LGTM 👍 
On to you @samueljlieber!

**Review by samueljlieber — APPROVED** [review]
Nice one @hojo-odoo, looks good to me! 👍
...
@robodoo r+

**Comment by samueljlieber** [comment]
@robodoo r-

**Comment by samueljlieber** [comment]
@hojo-odoo please resolve this build error before merge :)
https://runbot.odoo.com/runbot/build/66260146

Need to update the :doc: path in `essentials/search.rst` line 189:
```rst
their :guilabel:`Search...` bars. This includes the :doc:`Overall Equipment Effectiveness
<../inventory_and_mrp/manufacturing/workflows/oee>` report for the *Manufacturing* app, and the
``` 
🔽
```rst
their :guilabel:`Search...` bars. This includes the :doc:`Overall Equipment Effectiveness
<../inventory_and_mrp/manufacturing/reporting/oee>` report for the *Manufacturing* app, and the
```

**Review by samueljlieber — APPROVED** [review]
Thanks @hojo-odoo, looks good 👍 

Let's try this again... 😄

@robodoo r+

**Pull request closed without merging**
