### PR TITLE
[ADD] l10n_id: qris

### PR DESCRIPTION
**Pull request by nni-odoo**
Adding QRIS documentation from the following PR https://github.com/odoo/odoo/pull/146926

### CODE REVIEW

**Comment by nni-odoo** [comment]
closed due to documentation intended to target 17.0 instead of master

**Review by toaa-odoo — CHANGES_REQUESTED** [review]
Hi @nni-odoo! Thanks for your work. I corrected minor spelling mistakes and phrasing. As a reminder, don't forget to compress screenshots (pngquant).

I think there is some rebase issues, you can ping me again once it's fixed.

**Comment by nni-odoo** [comment]
@toaa-odoo noted on that and thank you for having a look!

**Review by jcs-odoo — APPROVED** [review]
I made some small changes + removed the prefix "indonesia-" from the media files.

@robodoo r+

**Pull request closed without merging**
