### PR TITLE
[IMP] conf: add sitemap generation

### PR DESCRIPTION
**Pull request by mart-e**
Well need to resolve issue about jdillard/sphinx-sitemap#22

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@mart-e aside from the conflicts is there anything blocking this?

**Comment by mart-e** [comment]
Not really, just need to install the dependency

**Comment by Feyensv** [comment]
Still needed/useful ? :thinking:

**Comment by xmo-odoo** [comment]
As much as it ever was: sitemaps are useful to SEO.

**Comment by mart-e** [comment]
Restarted at  #1067

**Comment by mart-e** [comment]
Is a sitemap really useful anyway? The documentation is correctly indexed, it's not like the forum where you need to point to every existing question, here every page is accessible from the index through the navbar and crawled by google.

**Pull request closed without merging**
