### PR TITLE
[IMP] accounting: change of the onboarding banners

### PR DESCRIPTION
**Pull request by afma-odoo**
task-4088605

### CODE REVIEW

**Review by auva-odoo — CHANGES_REQUESTED** [review]
Hello @afma-odoo, from what I can see, the text for the Invoicing banner needs to be adapted as well since the "steps" changed.
Currently, the following steps are described: Company data, Bank account, Invoice layout, Invoice creation
And in 17.0 - 17.3: Company Data, Documents Layout, Create Invoice, Online Payments
Let me know if you have any questions! :slightly_smiling_face:

**Comment by afma-odoo** [comment]
@auva-odoo I made the change for the invoice screenshot too, but maybe it didn't work. I can see that we changed the image name when I click on "View reviewed changes".

**Comment by auva-odoo** [comment]
@afma-odoo the screenshot is fine, but the text describing the Invoicing onboarding banner needs to be updated as the different steps shown on the new screenshot do not match the existing headings since they changed. The different sections under the Invoicing onboarding banner heading need to be updated as well (i.e., lines 125-181 in the get_started.rst file).

**Review by auva-odoo — CHANGES_REQUESTED** [review]
Hi @afma-odoo! Thank you for your work!
I suggest that instead of phrases like "This form/button takes you to..." or "Use this button to...," we go straight to the purpose of the button or form for all sections in the Invoicing banner.
E.g.: *This button takes you to the invoice creation view, where you can create your first invoice.* --> *Create your first invoice.*
(The same goes for Company data even though I know you didn't change it :wink: )
I also added some comments for the last section. Let me know if you have any questions! Thank you :slightly_smiling_face:

**Comment by afma-odoo** [comment]
Hi @auva-odoo Thanks for the comments & advice! :)

**Review by auva-odoo — APPROVED** [review]
@afma-odoo thank you for the changes! 
@robodoo r+

**Pull request closed without merging**
