### PR TITLE
[MOV] surveys: rename time_random to questions

### PR DESCRIPTION
**Pull request by ksc-odoo**
PROJECT TASK: https://www.odoo.com/odoo/project/3835/tasks/3958080?cids=3

This PR moves requested supplemental context/content suggested by SALI in the ﻿﻿PR #8215

### CODE REVIEW

**Comment by ksc-odoo** [comment]
Alrighty, @samueljlieber --- this quick fix PR is ready for a speedy Tech Review from you, whenever you get a chance. Thanks! 🙏

**Review by samueljlieber — CHANGES_REQUESTED** [review]
Hi @ksc-odoo! Nice job on this quick MOV PR. Your changes look great to me, I just have two quick fixes before I approve:

Please add a redirect in the `redirects/17.0.txt` file in the _Marketing_ section, in alphabetical order:
```txt
applications/marketing/surveys/time_random.rst applications/marketing/surveys/questions.rst   # time_random --> questions
```

Please update the commit message and PR title to match, and can simplify to (using `git commit --amend`):
```txt
[MOV] surveys: rename time_random to questions
```
Tag me for one more quick look after these are addressed, thank you!

**Comment by ksc-odoo** [comment]
Alrighty, @samueljlieber - I believe this one is ready for another look from you whenever you get a chance. Thanks! 👍

**Comment by samueljlieber** [comment]
c5380a1 Cherry picked previous commit f675763  and re-applied KSCs edits.

**Comment by samueljlieber** [comment]
..
@robodoo r+

**Pull request closed without merging**
