### PR TITLE
[IMP] Microsoft Azure Email Phrasing update

### PR DESCRIPTION
**Pull request by tiku-odoo**
Wording correction in Azure MS document Versions 15-17

Task:
https://www.odoo.com/web#cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form&id=3690205

### CODE REVIEW

**Comment by tiku-odoo** [comment]
@StraubCreative 

This PR is ready to merge. 

Correction of one word that was not correct.

**Comment by tiku-odoo** [comment]
@ksc-odoo @odoo/us-doc-review 

This small change is ready for your review. 

Thanks, 
Tim

**Review by samueljlieber — APPROVED** [review]
Thanks @tiku-odoo this PR looks good to me!

@StraubCreative this PR is good to go 👍

**Review by StraubCreative — APPROVED** [review]
@robodoo r+

**Comment by StraubCreative** [comment]
@robodoo retry

**Pull request closed without merging**
