### PR TITLE
[IMP] web: add tooltip on Dropdown

### PR DESCRIPTION
**Pull request by FrancoisGe**
This commit adds the possibility to add a tooltip on a Dropdown.

### CODE REVIEW

**Review by brboi — APPROVED** [review]

**Comment by FrancoisGe** [comment]
@odoo/doc-review

**Comment by Feyensv** [comment]
@robodoo delegate+

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r+

**Pull request closed without merging**
