### PR TITLE
[IMP] crm: add quotation product catalog

### PR DESCRIPTION
**Pull request by pabr-odoo**
Adding a block to the "Create and send quotations" doc explaining how the product catalog can be used to quickly add numerous products at once. Additionally adding a section explaining how to use sections to organize the order lines and update icons.

Task card: https://www.odoo.com/odoo/project/3835/tasks/4029850?cids=3

### CODE REVIEW

**Comment by pabr-odoo** [comment]
Hey @StraubCreative tagging you for first review on this addition. Thanks!

**Review by StraubCreative — APPROVED** [review]
Looks good @pabr-odoo, nice addition 👍 

Quick note on the commit title: this would be an **[IMP]** not an **[ADD]**, since we're improving on existing documentation files and not adding completely new ones. Consider fixing before tagging tech review since I'm sure it will come up.

**Review by samueljlieber — CHANGES_REQUESTED** [review]
Hi @pabr-odoo! Thanks for your work on this CRM doc to add info on product catalogs! Your changes look pretty good, I just have a few fixes for ya! 

Also, please update the commit message to match the type of PR this is:
(Commit message is different from the PR title, see the commit message in the [Commits tab](https://github.com/odoo/documentation/pull/10045/commits))
You can edit your commit message using: `git commit --amend`
```
[IMP] crm: add quotation product catalog
```
Tag me for one more quick look once these are addressed, thank you!

**Comment by pabr-odoo** [comment]
Hey @samueljlieber thanks for your thorough review! I implemented the suggestions and amended the commit message. Please let me know if there's anything else you need. Thanks!

**Review by samueljlieber — APPROVED** [review]
Nice one @pabr-odoo! Thanks for addressing my changes, everything looks good 👍
Thanks for your work!
..
@robodoo r+

**Pull request closed without merging**
