### PR TITLE
[ADD] Fleet: new services doc

### PR DESCRIPTION
**Pull request by larm-odoo**
Adding a new doc for the fleet app. This doc is all about services, how to create them, organize them, and configure them.

### CODE REVIEW

**Review by StraubCreative — APPROVED** [review]
@robodoo r+

**Comment by samueljlieber** [comment]
Resolved conflict in https://github.com/odoo/documentation/commit/20226a5b8e16920bb8e6c71972eb5362a2bb7381 due to another pr https://github.com/odoo/documentation/pull/5763 modifying `fleet.rst`. Should be fine to continue merging up to `master` 👍

**Comment by larm-odoo** [comment]
@robodoo retry

**Comment by larm-odoo** [comment]
@robodoo r+

**Comment by StraubCreative** [comment]
@robodoo r+

**Pull request closed without merging**
