### PR TITLE
[ADD] reference/orm: grouped method

### PR DESCRIPTION
**Pull request by xmo-odoo**
Method is added in odoo/odoo#101522

### CODE REVIEW

**Comment by ryv-odoo** [comment]
Can you rebase and update the doc with the new method name please ? To be able to merge it ?

**Comment by xmo-odoo** [comment]
:white_check_mark:

**Comment by ryv-odoo** [comment]
@robodoo r+

**Review by Feyensv — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
