### PR TITLE
[IMP] CRM: rewrite gamification config section

### PR DESCRIPTION
**Pull request by jero-odoo**
Addressing changes from this task: https://www.odoo.com/mail/view?model=project.task&res_id=3896512&access_token=41050eb3-596d-47cc-832b-c8d047165a39

Editing config section (regarding module installation), updating two screenshots.

### CODE REVIEW

**Comment by jero-odoo** [comment]
@StraubCreative This is ready for review. Thanks!

**Comment by StraubCreative** [comment]
@jero-odoo Conflict on #9040, addressing first before we can merge here...

**Review by StraubCreative — APPROVED** [review]
Looks good @jero-odoo 

I did catch a rendering issue on the bulleted list, on line 105. Will push up a fix momentarily.

Again, waiting on merge here until the FWPs from the previous PR are merged in first.

Thanks for the quick fix!

**Comment by StraubCreative** [comment]
Rebased to latest on [205f785](https://github.com/odoo/documentation/pull/9061/commits/205f78549a7d306d6deb192502c014957bdcf582), to include previous PR updates on this page.
All checks pass ✅ 
..
@robodoo r+

**Pull request closed without merging**
