### PR TITLE
[IMP] Sales: eBay Connector sync category edit

### PR DESCRIPTION
**Pull request by tiku-odoo**
Remove ebay category sync line from listings doc per QSA (product expert)
https://www.odoo.com/web#id=3252032&cids=3&model=project.task&view_type=form

### CODE REVIEW

**Comment by tiku-odoo** [comment]
@StraubCreative 

This doc is ready for your review. This is a change from the product expert on a recently published eBay doc. Removing the line that specifies the ebay product category menu populating.

**Comment by tiku-odoo** [comment]
@odoo/us-doc-review 

This small change is ready for your review! 

Thanks, 
Tim :+1:

**Review by samueljlieber — APPROVED** [review]
Hi @tiku-odoo, nice update, the change looks good to me! 

For the commit tag, I think [IMP] is more fitting since [REM] is usually used when removing a doc.

Approving now 👍 Please update the commit tag an PR title, then you can pass to final :)

**Comment by tiku-odoo** [comment]
@samueljlieber I updated the title, thanks. 

@StraubCreative This doc is ready for your review.

**Review by StraubCreative — APPROVED** [review]
Seems good. Thanks Tim!

@robodoo r+

**Pull request closed without merging**
