### PR TITLE
[ADD] accounting/l10n: add section in GSTR-1 report (India)

### PR DESCRIPTION
**Pull request by nash-odoo**
In this commit added the flow of generate spreadsheet view of GSTR-1 report.

**task**-3884120

### CODE REVIEW

**Comment by hamo-odoo** [comment]
@odoo/localizations-doc-review Can you please review this PR?

**Comment by nash-odoo** [comment]
Hello @toaa-odoo,
Thanks for the feedback, I'll keep it in mind next time.
I have changed the image, can you please have a look?
Thanks again. :blush:

**Review by toaa-odoo — APPROVED** [review]

**Comment by hamo-odoo** [comment]
@odoo/be-doc-review Can you please move this PR forward?

**Review by auva-odoo — CHANGES_REQUESTED** [review]
Hi @nash-odoo, could you please remove the markup (red box) from the screenshot and also compress the two image files you added? Thanks!

**Comment by nash-odoo** [comment]
Hello @auva-odoo,
Thanks for the review. I made the suggested changes, Can you please have a look?
Thanks again :blush:

**Review by auva-odoo — APPROVED** [review]
@nash-odoo LGTM, thank you! You can r+ whenever you're ready.
@robodoo delegate+

**Comment by nash-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
