### PR TITLE
[IMP] localization: AU rebrands Keypay to Employment Hero

### PR DESCRIPTION
**Pull request by tong-odoo**
task-3250954

### CODE REVIEW

**Comment by tong-odoo** [comment]
@fw-bot up to 13.0

**Comment by toaa-odoo** [comment]
Hi @tong-odoo, is there any particular reason you are targeting 13.0? AFAIK it does not build under 15.0 anymore

**Comment by tong-odoo** [comment]
Hi @toaa-odoo, it is because customers are checking on 13.0 documentation and found it quite confusing with the old name still existing.

**Review by toaa-odoo — APPROVED** [review]

**Comment by jcs-odoo** [comment]
I'm afraid the documentation is not supported and not built anymore for any version below 15.0.
Unless I'm mistaken, @AntoineVDV and the pages are still built?

**Comment by tong-odoo** [comment]
@jcs-odoo What should we do for version below 15.0 in this case? Because customers are confusing and keep asking our sales about Keypay and Employment Hero

**Comment by jcs-odoo** [comment]
> @jcs-odoo What should we do for version below 15.0 in this case? Because customers are confusing and keep asking our sales about Keypay and Employment Hero. Could we disable the access for 13.0?

How do they access this old documentation, then? Normally it shouldn't be found with a search on Google.

It's a recurring question: we'd rather archive the old doc, but it remains online nonetheless, I'm afraid.

**Comment by tong-odoo** [comment]
> > @jcs-odoo What should we do for version below 15.0 in this case? Because customers are confusing and keep asking our sales about Keypay and Employment Hero. Could we disable the access for 13.0?
> 
> How do they access this old documentation, then? Normally it shouldn't be found with a search on Google.
> 
> It's a recurring question: we'd rather archive the old doc, but it remains online nonetheless, I'm afraid.

I think the page link is from the KeyPay website. I will try to talk to them to update the link first. Thank you so much for your help

**Comment by jcs-odoo** [comment]
Or maybe not Payroll, after all ^^

**Pull request closed without merging**
