### PR TITLE
[REM] VoIP: Remove Asterisk Documentation

### PR DESCRIPTION
**Pull request by tiku-odoo**
Task per @bouvyd 

https://www.odoo.com/web#id=3679018&cids=3&model=project.task&view_type=form

### CODE REVIEW

**Comment by tiku-odoo** [comment]
@StraubCreative 
This change is ready for your review. This removes the Asterisk docs from versions 15-17, per Damien. 

Set as a priority (high) per Damien.

**Review by ksc-odoo — APPROVED** [review]
Hey there @tiku-odoo -- so, this seems like a pretty straightforward PR. Looks like you adequately deleted the necessary Asterisk mentions, per the request you were tagged in. I believe the tag on this PR should be [REM] not [RMV], though. So you may want to change that before moving this to tech review. Also, there's a slight adjustment needed in the 9th line of the axivox.rst that needs your attention. But other than that, I think this is good to go. Let me know if you have any questions. Thanks!

**Comment by bouvyd** [comment]
@tiku-odoo  muchas gracias for your reactivity!

**Comment by tiku-odoo** [comment]
@samueljlieber 

This PR is ready for your review. 

Simple removal of Asterisk doc

**Review by samueljlieber — APPROVED** [review]
Nice PR @tiku-odoo, the changes look good to me. 

I am approving now, and just confirming that I don't believe a redirect rule is necessary for this change since there is not an alternative for this removed doc, see the [rule here](https://github.com/odoo/documentation/blob/15.0/redirects/MANUAL.md):
> No redirect rule should be created when you delete a source file for which there is no alternative.

@StraubCreative this PR is good to go 👍

**Review by StraubCreative — APPROVED** [review]
LGTM 👍 Thanks all!

**Comment by StraubCreative** [comment]
@robodoo r+

**Pull request closed without merging**
