### PR TITLE
[IMP] buckaroo: provide steps to set up a webhook

### PR DESCRIPTION
**Pull request by luvnh**
Here is what Buckaroo Plaza looks like for reference:
screenshot-plaza buckaroo nl-2022 01 21-15_11_27

See also:
- https://github.com/odoo/odoo/pull/82922

task-2692127

### CODE REVIEW

**Comment by jcs-odoo** [comment]
Hello! Just checking this :)

**Comment by AntoineVDV** [comment]
> Hello! Just checking this :)

Liar!

**Comment by AntoineVDV** [comment]
Need to re-target to master.

**Comment by AntoineVDV** [comment]
Continued in https://github.com/odoo/documentation/pull/1481.

**Pull request closed without merging**
