### PR TITLE
[ADD] point_of_sale: Printer ePos without IoT in HTTPS

### PR DESCRIPTION
**Pull request by qle-odoo**
Add documentation to explain how to use a ePos printer in HTTPS

### CODE REVIEW

**Comment by jcs-odoo** [comment]
Need to change the Chrome part.
We'll temporarily add an external link for now. Waiting for @qle's input

**Comment by jcs-odoo** [comment]
Since I haven't received the new information about the Chrome part, we'll merge this doc as it is right now.

**Review by Feyensv — APPROVED** [review]
@robodoo delegate+

**Comment by jcs-odoo** [comment]
@robodoo r+

**Comment by Feyensv** [comment]
@robodoo delegate=jcs-odoo

**Pull request closed without merging**
