### PR TITLE
[FIX] 15.0 - Added Missing Parenthesis in Print() Function

### PR DESCRIPTION
**Pull request by altela**
Added parentheses in a print function

### CODE REVIEW

**Comment by Feyensv** [comment]
Thanks for trying to apply the change in the different versions of the doc, but we have a dedicated bot managing the forward-ports of changes in older versions.
Your changes will be applied in 15.0 with the PR https://github.com/odoo/documentation/pull/1927

**Comment by altela** [comment]
Hi @Feyensv thanks for reviewing.
Quick question : for future PR, should i create it from `main` branch instead of each supported version branch?

**Comment by AntoineVDV** [comment]
Hi @altela, you should always target [the oldest supported version of Odoo](https://www.odoo.com/documentation/master/administration/maintain/supported_versions.html#what-s-the-support-status-of-my-odoo) if your change is relevant in that version. Today, that means targeting 13.0.

**Comment by altela** [comment]
Will do! thanks @AntoineVDV 
Have a nice day!

**Pull request closed without merging**
