### PR TITLE
Clarify documentation of routes

### PR DESCRIPTION
**Pull request by mdb-odoo**
Starting at line 259 - updated the text. This text was a mix of incorrect and confusing statements. I changed some words and sentences to correct the text and make it make more sense. Also updated the rule name to Pull & Push as that is what it is called in Odoo.

### CODE REVIEW

**Comment by mdb-odoo** [comment]
@AntoineVDV PR for 13.0 - same as my 14.0 PR

**Comment by AntoineVDV** [comment]
13.0 port of https://github.com/odoo/documentation/pull/931

**Comment by AntoineVDV** [comment]
@Lau-Odoo Could you have a look at this?

**Comment by jcs-odoo** [comment]
coincoin

**Comment by jcs-odoo** [comment]
@fw-bot ignore

**Review by jcs-odoo — APPROVED** [review]

**Comment by AntoineVDV** [comment]
@robodoo delegate=jcs-odoo

**Comment by AntoineVDV** [comment]
@fw-bot ignore

**Pull request closed without merging**
