### PR TITLE
[DOC] cleanup of pec server documentation

### PR DESCRIPTION
**Pull request by amay-odoo**
PEC Server is removed from 16 (onwards)

### CODE REVIEW

**Review by toaa-odoo — APPROVED** [review]

**Review by xpl-odoo — CHANGES_REQUESTED** [review]
Hi @amay-odoo. Modifying .po files is not needed; this is handled automatically.

**Comment by amay-odoo** [comment]
Hello @xpl-odoo , thanks for the review, I've made the requested changes, could you please check now?

**Comment by xpl-odoo** [comment]
@robodoo r+

**Comment by xpl-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
