### PR TITLE
[ADD] l10n_mx: correct test credentials

### PR DESCRIPTION
**Pull request by feav-odoo**
For 14.0 to 16.0

### CODE REVIEW

**Review by toaa-odoo — APPROVED** [review]

**Comment by jco-odoo** [comment]
Not sure if test certificates are still needed in the documentation, but at least better to update them if they are there.

**Comment by feav-odoo** [comment]
@toaa-odoo Hello can we get a +r? Old credentials are quite misleading for new customers. 
We are doing a renewal of l10n_mx already in #5225 , but it's gonna take a little bit to become live.

Thank you!

**Comment by xpl-odoo** [comment]
@robodoo r+

**Comment by xpl-odoo** [comment]
@robodoo delegate+

**Comment by feav-odoo** [comment]
This is being added in the corrections of #5225

**Pull request closed without merging**
