### PR TITLE
[ADD] Spreadsheet: templates

### PR DESCRIPTION
**Pull request by xpl-odoo**
task-3235170

### CODE REVIEW

**Comment by jcs-odoo** [comment]
Coucou @xpl-odoo 

"New" is not a tag we use. Please use [ADD] instead.
You should see the list in your [default commit message](https://github.com/odoo/documentation/blob/16.0/commit_template.txt) if it's correctly set.

Salut

**Comment by xpl-odoo** [comment]
@LoredanaLrpz shall we merge it as it is? ^^

**Review by LoredanaLrpz — APPROVED** [review]

**Comment by LoredanaLrpz** [comment]
@xpl-odoo since you're an author, I cannot ask for your review, but could you look at the changes, please? Thanks!

**Comment by xpl-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
