### PR TITLE
[IMP] l10n_cl: Add library needed to print the PDF report

### PR DESCRIPTION
**Pull request by vbe-odoo**
If the user is hosted in Odoo SH or On-Premise, he should manually install a library and this document will help the support team to easily refer the users on how to do it.

### CODE REVIEW

**Comment by vbe-odoo** [comment]
Hi @jcs-odoo I hope you are doing well! :D
Can you help with this minor addition (an important section)
Let me know if there are any changes needed.

Thanks!
Bests!
--
@JPML94

**Review by jcs-odoo — APPROVED** [review]
Hello @vbe-odoo 
Thank you for your patience :)
I made some changes directly, instead of writing feedback.
I changed the commit message and description as the internal reason is meaningless in a commit message (the part about the support team).
Als, I replaced your quote makes with the appropriate [markup](https://www.odoo.com/documentation/14.0/contributing/documentation/rst_cheat_sheet.html#markup).

Thanks

**Comment by jcs-odoo** [comment]
@odoo/doc-review 
The check has failed because of the name of the branch, which is the default name when creating a patch directly on GitHub.

**Comment by vbe-odoo** [comment]
@jcs-odoo thanks for the update on this one and for the corrections 👍 !
Best!

**Pull request merged**
