### PR TITLE
[FIX] voip: update broken links, light markup cleaning

### PR DESCRIPTION
**Pull request by StraubCreative**
[Task 3479917](https://www.odoo.com/web#id=3479917&cids=3&model=project.task&view_type=form)

- Fix broken external links
- 100th character cleanup

Note: this doc needs a complete refresh. More details in Task @tiku-odoo

### CODE REVIEW

**Comment by StraubCreative** [comment]
@robodoo r+

**Comment by StraubCreative** [comment]
@robodoo retry

**Comment by StraubCreative** [comment]
@robodoo retry

**Comment by StraubCreative** [comment]
@robodoo delegate=samueljlieber

**Comment by samueljlieber** [comment]
Looks good to me! @robodoo r+

**Review by samueljlieber — APPROVED** [review]

**Comment by StraubCreative** [comment]
@robodoo r+

**Comment by StraubCreative** [comment]
@robodoo r+

**Comment by StraubCreative** [comment]
@robodoo r+

**Comment by StraubCreative** [comment]
😄 

@robodoo retry

**Pull request closed without merging**
