### PR TITLE
[IMP] IOT Printer Doc Update

### PR DESCRIPTION
**Pull request by tiku-odoo**
Add clarification per: 
https://github.com/odoo/documentation/pull/7251/files

Task: https://www.odoo.com/web#cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form&id=3690324

### CODE REVIEW

**Comment by tiku-odoo** [comment]
@lse-odoo 

Hi Loan, 
Can you review this doc when you have a chance? Just added some additional information per: 

https://github.com/odoo/documentation/pull/7251

**Comment by lse-odoo** [comment]
@tiku-odoo I am not sure of the behavior in version < 17.0, I guess it would be better to ask to the functional support the intended behavior in this versions :/

**Comment by tiku-odoo** [comment]
@wigu-odoo 

Can you review this doc when you have a moment?

**Comment by wigu-odoo** [comment]
Hello @tiku-odoo 

I will test again on Monday when I am back in the office (thanks snowstorms) but it does look mostly correct! 

The one thing I did notice from when I tested this about a month ago in a ticket that I needed to escalate was that the popup to select printer does not appear unless I have developer mode active. 

In the ticket I have a video from runbot when I have dev mode enabled as well as a screenshot from runbot and in the screenshot, I do not get the popup since I don't have developer mode enabled, but in my recording, I do when I have developer mode enabled. 

The debug icon is also present in my recording with this popup. 

I am pretty sure developer mode needs to be enabled for the popup to select the printer, but I will test more when I am in the office on Monday to confirm.

**Comment by lse-odoo** [comment]
@wigu-odoo if I am not mistaken, the pop-up show once then save into the browser cookie your result. So maybe the fact to switch to developer mode is not true and made you think that it was needed

**Comment by wigu-odoo** [comment]
@lse-odoo You were indeed correct, developer mode is not necessary for the popup. 

@tiku-odoo this is indeed correct!

**Review by wigu-odoo — APPROVED** [review]
just tested to be sure developer mode is not necessary, everything looks correct!

**Review by StraubCreative — APPROVED** [review]
LGTM 👍 

@robodoo r+

**Pull request closed without merging**
