### PR TITLE
[IMP] accounting/l10n_cl: Fiscal PDF report image

### PR DESCRIPTION
**Pull request by masi-odoo**
Adds image of accepted invoice PDF report with the fiscal elements needed. It replaces the last image used, which had sensitive information of a third party company.

Link to image: https://drive.google.com/file/d/1JYymyUVz_3q6bBg-yrgM_i6Di9gLcqOc/view?usp=sharing

### CODE REVIEW

**Review by samueljlieber — APPROVED** [review]
Hi @masi-odoo, thanks for the PR to add this image. In fe10c06 I resized and compressed the image and added it to the PR 👍

**Comment by samueljlieber** [comment]
1ec44d9  Updated commit tag from `[ADD]` to `[IMP]`

**Comment by masi-odoo** [comment]
Hello @samueljlieber thanks for the support! Let me know if you need anything else on my side.

Also just clarifying I made the PR on 15 but it should also apply to V16, V17 and Master.

Thanks again!

**Review by dade-odoo — APPROVED** [review]
Passing this on to @auva-odoo for final review and r+ :)

**Review by auva-odoo — APPROVED** [review]
Hi @masi-odoo @samueljlieber I force-pushed to remove the center-alignment as we don't use it anymore (guidelines are being reviewed). Thank you guys for your work!
@robodoo r+

**Comment by masi-odoo** [comment]
Hello @auva-odoo @samueljlieber thank you so much for the advise and support!

**Pull request closed without merging**
