### PR TITLE
[IMP] install/maintain: add section about search engine indexation

### PR DESCRIPTION
**Pull request by jcs-odoo**
task-3179504

### CODE REVIEW

**Comment by toaa-odoo** [comment]
All good to me, but maybe you should add a :seealso: to this page ? http://localhost:63342/documentation/_build/html/applications/websites/website/optimize/seo.html It's outdated in some aspects, but still relevant

**Review by toaa-odoo — APPROVED** [review]

**Comment by jcs-odoo** [comment]
> All good to me, but maybe you should add a :seealso: to this page ? http://localhost:63342/documentation/_build/html/applications/websites/website/optimize/seo.html It's outdated in some aspects, but still relevant

Good idea thanks :)

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by jcs-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
