### PR TITLE
[IMP] documents: new changes in V17

### PR DESCRIPTION
**Pull request by Donapi**
[taskid: 3491654](https://www.odoo.com/web#id=3491654&cids=1&model=project.task&view_type=form)
Documentation of the changes in V17

### CODE REVIEW

**Comment by xpl-odoo** [comment]
@robodoo delegate+

**Comment by Donapi** [comment]
@robodo r+

**Comment by xpl-odoo** [comment]
> @robodo r+

It's @robodoo r+
:)

**Comment by auva-odoo** [comment]
Hey @Donapi this PR hasn't been merged yet (and has conflicts); is it intended?  If yes, should it be closed?

**Comment by Donapi** [comment]
@robodoo r+

**Pull request closed without merging**
