### PR TITLE
[FIX] accounting/l10n_cl: remove company image

### PR DESCRIPTION
**Pull request by samueljlieber**
Task: [#4078019](https://www.odoo.com/odoo/project/3835/tasks/4078019?cids=3)

This PR removes an image from the Chile documentation.

### CODE REVIEW

**Review by masi-odoo — APPROVED** [review]
Perfect! Thank you @samueljlieber

**Comment by masi-odoo** [comment]
@samueljlieber can this be FW ported all the way to Master?

Thanks!

**Comment by samueljlieber** [comment]
> @samueljlieber can this be FW ported all the way to Master?

Yes! In 16.0 and up the filename is `sii-validation-elements.png`, and will be removed 👍

**Review by StraubCreative — APPROVED** [review]
LGTM, skipping l10n review since the change is so small and the image in question has customer data in it (seems like a priority to remove)

@robodoo r+

**Comment by masi-odoo** [comment]
Thanks for the help @samueljlieber @StraubCreative !

CC @ren-odoo

**Pull request closed without merging**
