### PR TITLE
[IMP] backend: add `default_group_by` option in list view

### PR DESCRIPTION
**Pull request by xavierbol**
Related PR: https://github.com/odoo/odoo/pull/109281

task-3084850

### CODE REVIEW

**Comment by xavierbol** [comment]
Hello @VincentSchippefilt and @Julien00859 ,

Can I have a quick review? 🙂 

I would like to merge the related PRs for saas~16.1. 🙂 😇 

Thanks in advance! 🙂 

Have a nice day!

**Review by Julien00859 — APPROVED** [review]

**Comment by Julien00859** [comment]
I don't remember if we have to wait for the documentation team or not... in anyway I would had r+ myself so...

@robodoo delegate+

**Comment by Julien00859** [comment]
ok so we have to wait for the documentation team ahah :D

**Comment by AntoineVDV** [comment]
@robodoo r+

@Julien00859 Always ping `@doc-review` when you approve a PR ;) I let you guys review first in case you want to ask for changes.

**Pull request closed without merging**
