### PR TITLE
[IMP] to-do: create a new to-do with ctrl k shortcut

### PR DESCRIPTION
**Pull request by Donapi**
[taskid-3501306](https://www.odoo.com/web#id=3501306&cids=1&model=project.task&view_type=form)

### CODE REVIEW

**Review by toaa-odoo — APPROVED** [review]

**Review by jcs-odoo — APPROVED** [review]
@robodoo r+

**Comment by jcs-odoo** [comment]
robodoo retry

**Comment by jcs-odoo** [comment]
robodoo retry

**Comment by Xavier-Do** [comment]
robodoo retry

Happy new year

**Comment by jcs-odoo** [comment]
> robodoo retry
> 
> Happy new year

merci, toi aussi :D

**Pull request closed without merging**
