### PR TITLE
[ADD] pos: list of compatible epos printers

### PR DESCRIPTION
**Pull request by LoredanaLrpz**
task-3691914

### CODE REVIEW

**Comment by LoredanaLrpz** [comment]
Hey @tiku-odoo , thank you so much for your work!
Have a great day

**Review by jcs-odoo — APPROVED** [review]
@robodoo r+

**Comment by jcs-odoo** [comment]
@robodoo r-

**Review by tiku-odoo — APPROVED** [review]

**Comment by jcs-odoo** [comment]
@robodoo r+

**Comment by jcs-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
