### PR TITLE
[FIX] developer/frontend: small typos

### PR DESCRIPTION
**Pull request by poma-odoo**

### CODE REVIEW

**Review by sdegueldre — APPROVED** [review]
code changes seem fine, not sure about commit conventions on this repo though.

**Comment by jcs-odoo** [comment]
@poma-odoo @sdegueldre 

commit title conventions are here https://github.com/odoo/documentation/blob/15.0/commit_template.txt 
Also, as code owner for javascript-doc-review , you have to add odoo/doc-review as the reviewer once you've approved the PR. They'll take care of the merge :)

**Review by jcs-odoo — CHANGES_REQUESTED** [review]
please change the commit title (and PR title as well) to something such as

`[FIX] dev ref/js framework: typo in registries`

**Review by Feyensv — APPROVED** [review]
@robodoo r+ squash

**Comment by poma-odoo** [comment]
> please change the commit title (and PR title as well) to something such as
> 
> `[FIX] dev ref/js framework: typo in registries`

I guess it is too late, it is already squashed for good, but I'll keep in mind for the next

**Comment by Feyensv** [comment]
It's better if it's clean directly, but was faster for us here to directly fix it without requesting/doing a force-push only to update the commit :).
Thanks :+1:

**Pull request closed without merging**
