### PR TITLE
[IMP] reference/user_interface: 17.0 odoo ui icons

### PR DESCRIPTION
**Pull request by samueljlieber**
Task: [#3912373](https://www.odoo.com/web?debug=1#id=3912373&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form)
[IMP] suggested from https://github.com/odoo/documentation/pull/9065#pullrequestreview-2040266043

This PR improves the `icons.rst` documentation of the Odoo UI icon list by adding the [new 17.0 icons](https://github.com/odoo/odoo/blob/17.0/addons/web/static/lib/odoo_ui_icons/style.css#L24-L61) as well as the RTL adaptations.

Note: is there a reason to keep the old `16.0` styles for the `.oi-close` icon? I don't see these styles in the [Odoo css](https://github.com/odoo/odoo/blob/6f6763b6728335b0728645806d77a0cb7453ffc7/addons/web/static/lib/odoo_ui_icons/style.css#L61):
``` css
.oi-close:before {
  content: '\00d7';
  font-family: sans-serif;
  font-weight: bold;
}
```

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]
@robodoo delegate+

**Comment by samueljlieber** [comment]
Hi @odoo/design-doc-review, just checking if you have any comments on this PR before I merge. Thank you!

**Comment by Brieuc-brd** [comment]
Hello @samueljlieber 👋 
I would have liked to test your branch on runbot but it doesn't seem to work 🥲 , could you take a look at it?
Capture d’écran 2024-06-14 à 14 47 11

**Comment by samueljlieber** [comment]
Hi @Brieuc-brd, sorry about that! 🙂 The build must have been deactivated after some time, I rebased the PR and it should be available for you here: https://runbot120.odoo.com/runbot/static/build/64019617-17-0/logs/build/html/developer/reference/user_interface/icons.html

Thank you in advance!

**Review by Brieuc-brd — APPROVED** [review]
Hey @samueljlieber 👋 
Thanks for your work, LGTM 👍 

> Note: is there a reason to keep the old 16.0 styles for the .oi-close icon? I don't see these styles in the [Odoo css](https://github.com/odoo/odoo/blob/6f6763b6728335b0728645806d77a0cb7453ffc7/addons/web/static/lib/odoo_ui_icons/style.css#L61):

This icon has been updated months ago : https://github.com/odoo/odoo/pull/144598 targeting `17.0`.
So to me, there's no reason to keep the old close icon here :)

**Comment by samueljlieber** [comment]
@robodoo r+

**Pull request closed without merging**
