### PR TITLE
[IMP] manufacturing: add missing word in flexible_components_consumption

### PR DESCRIPTION
**Pull request by jedgalbraith**
I believe the author intended it to say "asks you *for* one more desk" instead of "asks you one more desk".

### CODE REVIEW

**Review by jcs-odoo — APPROVED** [review]

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by AntoineVDV** [comment]
@robodoo r+

**Comment by AntoineVDV** [comment]
@robodoo r-

**Comment by AntoineVDV** [comment]
@robodoo r+

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
