### PR TITLE
[IMP] web: kanban: document new "can_open" attribute

### PR DESCRIPTION
**Pull request by aab-odoo**
(Part of) task `3650117`

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]
@robodoo delegate+

**Review by ged-odoo — COMMENTED** [review]
maybe mention the change kanban-box -> kanban-card?

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo rebase-ff

**Pull request closed without merging**
