### PR TITLE
[IMP] productivity: voip OnSIP US only block

### PR DESCRIPTION
**Pull request by tiku-odoo**
Task: 
https://www.odoo.com/web#id=3857532&cids=3&menu_id=4720&action=333&active_id=3835&model=project.task&view_type=form

### CODE REVIEW

**Comment by tiku-odoo** [comment]
@StraubCreative 

This PR is ready for your review. A small block was added per a request through the documentation channel in (BE). I've confirmed the info with the OnSIP rep as well. 

Thanks, 
Tim :+1:

**Review by StraubCreative — APPROVED** [review]
Looks good, thanks @tiku-odoo 👍

**Review by samueljlieber — APPROVED** [review]
Looks good to me @tiku-odoo, thanks!
..
@robodoo r+

**Comment by tiku-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
