### PR TITLE
[FIX] odoo_theme: fix logo colors

### PR DESCRIPTION
**Pull request by anso-odoo**
Before this commit, the Odoo logos used in the documentation were using the old purple color.

This commit updates all these old logos with the latest version that can be found on the Odoo brand-asset page

https://www.odoo.com/page/brand-assets

task-3328677
Community related PR: https://github.com/odoo/odoo/pull/132063

### CODE REVIEW

**Review by jcs-odoo — CHANGES_REQUESTED** [review]
Looks good to me, thanks @anso-odoo 
Could you just target 14.0 instead of 16.0, please? Thanks

**Comment by anso-odoo** [comment]
Hello @AntoineVDV can you have a look at this one please ? :) Thanks

**Review by jcs-odoo — APPROVED** [review]

**Review by AntoineVDV — APPROVED** [review]
@robodoo delegate+

**Comment by anso-odoo** [comment]
Closing it temporarly as this PR needs to target 14.0 and the community one needs to target 16.0. I will reopen it once the community is merged

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
