### PR TITLE
[FIX] *: RST cleanup

### PR DESCRIPTION
**Pull request by jcs-odoo**
RST cleanup to comply with the RST guidelines. This is required so we can use "make test", as there are currently hundreds of errors. For now, it is unusable because of the oldest code in this repo.

### CODE REVIEW

**Comment by jcs-odoo** [comment]
@AntoineVDV 

If the "legal" commit is picked:
image

But again, the 100th length may be broken ^^

**Comment by jcs-odoo** [comment]
@odoo/doc-review 

It's ready for review, but I leave it as a draft, so it doesn't ping all code owners. I guess it's still possible to r+?

**Comment by Feyensv** [comment]
Nope, we cannot r+ draft PR's anymore (was possible at some point in the past but not now).
But there is a special trick where we can ask the runbot team to disable codeowners on a bundle/branch ;)

**Comment by jcs-odoo** [comment]
Bah it's okay, they'll delete a notification email, that's not so bad :p

> Nope, we cannot r+ draft PR's anymore (was possible at some point in the past but not now). But there is a special trick where we can ask the runbot team to disable codeowners on a bundle/branch ;)

**Comment by Feyensv** [comment]
ok, i got the rights for it :sunglasses:
Codeowners should disabled on this branch now :ok_hand:

**Comment by jcs-odoo** [comment]
> ok, i got the rights for it 😎 Codeowners should disabled on this branch now 👌

Thanks!

@robodoo r+

**Pull request closed without merging**
