### PR TITLE
[IMP] inventory: putaway rules

### PR DESCRIPTION
**Pull request by Felicious**
### Summary of changes
1. Address @GillesMerckxOdoo's feedback about putaway rule priority
2. Add more details to instructions  
3. Update heading formatting to match new standards

### CODE REVIEW

**Comment by brse-odoo** [comment]
Hi @Felicious, I'll review this right away!

**Review by brse-odoo — APPROVED** [review]
Hi @Felicious, I've finished my review of this PR. Great job! All your additions/changes to the doc were clear and concise -- I thought the `example` admonitions were especially helpful and informative.

I only had some minor suggestions for you to accept/reject as you see fit, so I'm approving this for the next round. Feel free to reach out if you have any questions, thanks!

**Comment by Felicious** [comment]
Hello @odoo/us-doc-review! This PR is ready for you, whenever you have a chance

**Review by StraubCreative — APPROVED** [review]
Hi @Felicious 
Great rewrite. I found that the instructions were clear and succinct, and the examples you added were helpful.
...
@robodoo r+

**Pull request closed without merging**
