### PR TITLE
[IMP] accounting/l10n_cl: add Important note to F29 report

### PR DESCRIPTION
**Pull request by rps-odoo**

### CODE REVIEW

**Review by samueljlieber — APPROVED** [review]
Looks good to me @rps-odoo! Thank you!

**Comment by masi-odoo** [comment]
Hello @rps-odoo @samueljlieber hope you are great!

I think it looks strange if the important note is added before the image (since the past text line is referring to the image of the report), is it possible we can move it below the image?

image

Thanks!

**Comment by samueljlieber** [comment]
> is it possible we can move it below the image?

Hi @masi-odoo! Text takes precedence over an image in documentation, and text instructions should be able to stand alone, and be clear enough without a supporting image. In my opinion , it would look strange to have the important admonition come after the image. I will leave it up to the l10n doc review team to offer a suggestion here :)

**Comment by masi-odoo** [comment]
Got it @samueljlieber!

Thanks for the clarification, if that is the case, I think we could move it to this section, before it starts explaining the report with screenshots:

image

Thanks again!

**Comment by samueljlieber** [comment]
@masi-odoo I like it 😄, in https://github.com/odoo/documentation/commit/2401a810bbfd0c6eb7dd4368f6c35ce38119c578 I moved the important admonition higher up in the _Propuesta F29_ section as well as added "Propuesta F29" in the admonition to specify exactly the report being referred to. Thanks!

**Comment by masi-odoo** [comment]
@samueljlieber looks great! As always, thanks!

**Review by dade-odoo — APPROVED** [review]
Looks good to me! Thanks @samueljlieber @masi-odoo @rps-odoo :)

**Review by auva-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
