### PR TITLE
[IMP] Rework the JavaScript tutorials

### PR DESCRIPTION
**Pull request by fdardenne**
This commit rework the entire JavaScript tutorial series with the following improvements:

-   Each chapter is now designed to be independent, allowing learners to
    follow any chapter without the necessity of completing previous ones.
-   Each chapter has been transformed into a standalone module, enabling
    learners to create small projects from scratch within each chapter.
-   The screenshots/text/code have been updated for Odoo 17.

Currently we have 5 chapters:
- Discover Chapter 1 - Owl Components: This chapter allows to learn the Owl framework in the `awesome_owl` module.
- Discover Chapter 2 - Build a dashboard: This chapter allows to grasp the basic of the web framework by building a dashboard in the `awesome_dashboard` module.
- Master Chapter 1 - Build a clicker game: This chapter allows to grasp the web framework by building a clicker game in the `awesome_clicker` module.
- Master Chapter 2 - Create a gallery view: This chapter allows to learn how to create a new view type. The new view is a gallery of records pictures. It can be done in the `awesome_gallery` module.
- Master Chapter 3 - Customize a kanban view: This chapter allows to learn to customize a kanban view by implementing a list of customer in the side of a kanban view. This can be done in the `awesome_kanban` module.

The chapter on creating and customizing fields is deleted for now and will be completely rewritten in a near future.
The chapter on testing is deleted, how-to guides will be written to cover this subject.

The solutions for all exercises has been done for v17, the goal by merging the new tutorial is to have this new branch structure in `odoo/tutorials`:
- 16.0
- 16.0-solutions
- 17.0
- 17.0-discover-js-framework-solutions
- 17.0-master-odoo-web-framework-solutions
-   master <-- default branch, starting point for all addons
-   master-discover-js-framework-solutions
-   master-master-odoo-web-framework-solutions

task-id: 3623595

### CODE REVIEW

**Review by ged-odoo — APPROVED** [review]

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by AntoineVDV** [comment]
Hello @ged-odoo, @fdardenne asked if I could go through the PR with him before merging.
Also, I wanted to ask the new devs who are doing their technical training at the moment to follow this tutorial instead of the old one to proofread the PR; what do you think?

**Comment by AntoineVDV** [comment]
Florent asked me the same day he created the PR if we could have a look together (that is planned in two days), which I agreed with, so I don't think I'm blocking anything... But if I am, or if you need to merge this ASAP, feel free to do so ->
@robodoo delegate+
@robodoo delegate=ged-odoo
Or ask runbot team for merge rights directly 

However, I will not make post-merge reviews because it implicitly shifts the responsibility of cleaning content and fixing mistakes onto me. In theory, it should speed up the merge process (which I believe is only a fraction of that of other repositories) but, in practice, it just makes me chase contributors for weeks (not all the time, not all contributors, but still) so they create a follow-up PR, or fix the build of the documentation because someone added an extension that works only on some systems. Also it's quite cumbersome because we need to create and forward-port extra PRs, handle redirects when renaming files, review again... you get my point.

Understand that I'm not pointing fingers at your team in particular, especially since you usually deliver clean PRs, but you'd be surprised to see the PRs I sometimes have - and am relieved - to block before merging. My goal is not to hinder contributions to the documentation (quite the opposite actually, I'm uncomfortable doing so) but I do aim to make the documentation better over time, and I strongly believe that removing reviews from the process is a step in the bad direction the documentation was taking a few years ago.

Correct me if I'm wrong or if I misunderstood something, but I feel I had to clearly express my opinion on the matter.

**Comment by ged-odoo** [comment]
robodoo r+ 
thanks. we can talk about it some day, easier to debate in person :)

**Pull request closed without merging**
