### PR TITLE
[IMP] l10n_my: MyInvois documentation

### PR DESCRIPTION
**Pull request by kidoodoo**
Recently, there has been a new module to support MyInvois which is legally mandatory for Malaysia. With its release this week, documentation is required for the users to add specific information to register Odoo as an intermediary but also to let them know how the set-up is and the business flow achievable in Odoo.

task-3953659

### CODE REVIEW

**Review by afma-odoo — CHANGES_REQUESTED** [review]
Hi! Thank you @kidoodoo for your work on creating this Malaysian localization page! I added some comments/suggestions. Please check out our [content guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html) and [RST guidelines and cheat sheet](https://www.odoo.com/documentation/master/contributing/documentation/rst_guidelines.html) for more information.
Please let me know if you have any questions.
Thanks!

**Review by afma-odoo — COMMENTED** [review]
@kidoodoo Thanks for the updates. Could you add some additional information about the "Identification" and "Ind. Classification" fields in the "Contact & Company Information"? I think it might help users. Thank you!
I'll let you know as soon as I can update the page with the "Customer Invoices" page reference.

**Comment by kidoodoo** [comment]
@afma-odoo 

Thank you! I made the last change as per your request on "Identification" and "Ind. Classification" with more details.

Could I know if we could request to merge this documentation first and then make an amendment for "Customer Invoices" section once the reference page is ready? There is an information included in this document (Name, TIN, BRN) in order to register Odoo as an intermediary on the MyInvois portal and it is part of the necessary process to submit the e-invoices.

Would appreciate your help in this, thank you in advance!

**Review by afma-odoo — APPROVED** [review]
@kidoodoo Thanks for the last update ;) 
I force-pushed some changes to fix minor issues. I updated the "Send invoices to MyInvois" section and referenced the current "Customer Invoices" page. I'll check when the updated "Customer Invoices" page is online to see if it still works.
I approve the PR and add the be-doc review. 
Thanks again :)

**Comment by kidoodoo** [comment]
@afma-odoo 

Thank you so much for your patience and help! 
I will use this PR as a reference so that for the future documentation, things are done well in the first go.

Appreciate it, have a great day!

**Comment by afma-odoo** [comment]
@kidoodoo You're welcome ;) Don't hesitate to ask if you have any questions!
Have a great day!

**Review by auva-odoo — APPROVED** [review]
Hi @kidoodoo thank you very much for your work (and thank you @afma-odoo for the first review! :slightly_smiling_face: ). I pushed some more minor changes, mainly to:
- remove capital letters in titles and the `guilabel` for app names;
- simplifiy/clarify the text (and sometimes);
- correct a few typos and missing commas.

If you're okay with my changes, you can r+ whenever you're ready.

@robodoo delegate+

**Comment by kidoodoo** [comment]
@robodoo r+

**Pull request closed without merging**
