### PR TITLE
[IMP] accounting: update reporting page and screenshots

### PR DESCRIPTION
**Pull request by afma-odoo**
task-3605633
task-3562956

### CODE REVIEW

**Comment by afma-odoo** [comment]
@auva-odoo This concerns tasks 3605633 & 3562956. Some additional changes will be needed from 17.0.
Thanks!

**Review by auva-odoo — CHANGES_REQUESTED** [review]
Hello @afma-odoo great job on this PR! I added a few comments and suggestions in my review as usual, and I also suggest removing all screenshots and related image files under each report. 
Could you also add the second task you mentioned in a comment on this PR in the commit message + PR description? Thank you!

**Review by auva-odoo — APPROVED** [review]
Great job @afma-odoo, thank you! @robodoo r+

**Comment by afma-odoo** [comment]
@auva-odoo Thank YOU! ;)

**Comment by auva-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
