### PR TITLE
[ADD] odoo.sh: new ci token usage

### PR DESCRIPTION
**Pull request by sts-odoo**

### CODE REVIEW

**Comment by amigrave** [comment]
@robodoo squash

**Comment by amigrave** [comment]
@xmo-odoo thanks !

CleanShot 2024-10-10 at 15 11 55

**Comment by amigrave** [comment]
@robodoo fais la bise à XMO s'il te plaît !

**Comment by amigrave** [comment]
@robodoo t'es vraiment nul !

**Review by amigrave — APPROVED** [review]

**Comment by xpl-odoo** [comment]
Very minor suggestions, delegating already.
@robodoo delegate=sts-odoo,amigrave

**Comment by amigrave** [comment]
@robodoo r+

**Pull request closed without merging**
