### PR TITLE
[IMP] quote_template: changes Quotation Builder to PDF Quote Builder

### PR DESCRIPTION
**Pull request by Demesmaeker**
Quotation Builder feature is replace by the PDF quote builder feature

task-3249142

See also:

- https://github.com/odoo/odoo/pull/133773
- https://github.com/odoo/upgrade/pull/5168

### CODE REVIEW

**Comment by jcs-odoo** [comment]
Hi @Demesmaeker 
@dalaOdoo  told me you had a doc pr for the feature, but I see it's mostly to remove the content about the old builder.
I created a task (still unassigned) for the new content to write --> https://www.odoo.com/web#id=3523173&menu_id=4720&cids=1&action=333&active_id=3835&model=project.task&view_type=form

**Comment by Demesmaeker** [comment]
Hello @jcs-odoo 
Thanks, I don't have the time to do the full documentation PR at the moment, I intended to create the task once the feature is merged, as this probably isn't the final version, and I thought it was best to wait for something visually similar to the end product. So I just took off what was now wrong in the documentation.
I'll link that doc task to this feature task. =]
Have a nice day!

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by StraubCreative** [comment]
Hi everyone.

Please loop us in next time instead of just merging content changes that are assigned to our scope.

I wasn't aware this needed a review until it got merged in. Obviously it's an easy approval, but surprises like this aren't very fun. Regarding the [Task linked here](https://github.com/odoo/documentation/pull/5863#issuecomment-1736913081), this is the first time I'm seeing that too...again, not fun 🙃  

Thank you for your understanding.

cc: @meng-odoo @ksc-odoo @jubodoo

**Pull request closed without merging**
