### PR TITLE
[DEL] MRP: Delete Quality Control doc

### PR DESCRIPTION
**Pull request by hojo-odoo**
This PR deletes the "[Quality Control](https://www.odoo.com/documentation/16.0/applications/inventory_and_mrp/manufacturing/management/quality_control.html)" doc in the "Manufacturing management" folder of the Manufacturing app documentation for version 16.0. The information in this doc has been rewritten and expanded upon in the "[Add quality controls](https://www.odoo.com/documentation/16.0/applications/inventory_and_mrp/manufacturing/quality_control/quality_control_points.html)" doc, located in the dedicated "Quality control" folder. Any references to the Quality Control doc in the documentation file tree have also been removed.

### CODE REVIEW

**Comment by hojo-odoo** [comment]
Hey @StraubCreative,

This should be a quick approval. The only change is deleting a doc that has now been made redundant.

Thanks,
hojo

**Review by StraubCreative — CHANGES_REQUESTED** [review]
Hi @hojo-odoo 
Looks good we'll just need to add a redirect for the deleted file to point to the new/rewritten one. After that should be good, thanks!

**Comment by hojo-odoo** [comment]
Hey @StraubCreative,

I've added the redirect for the deleted doc.

Thanks,
hojo

**Review by StraubCreative — APPROVED** [review]
Looks good to me.
@samueljlieber same here can you take a look please and merge only for 16.

@robodoo delegate=samueljlieber

**Review by samueljlieber — APPROVED** [review]
Looks good to me! Nice job @hojo-odoo 🙂 
@fw-bot ignore
@robodoo r+

**Comment by samueljlieber** [comment]
@robodoo retry

**Pull request closed without merging**
