### PR TITLE
[FIX] payment_providers: authorize import template link

### PR DESCRIPTION
**Pull request by benderliz**
Task in Odoo: https://www.odoo.com/odoo/project.task/4393603

FWP to `master`

### CODE REVIEW

**Comment by benderliz** [comment]
Hi @samueljlieber! I sent a message on the Odoo task as well, but I think this PR just need a quick review before it can be merged. Thanks so much for your advice to switch the target branch on GitHub! :)

**Review by samueljlieber — APPROVED** [review]
Thanks for getting this PR up and running @benderliz! 

I apologize as I should have been clearer in my task– I made a commit to update the Google sheet link to an `.xlsx` spreadsheet of the template I uploaded to the docs media folder :)

**Comment by samueljlieber** [comment]
Hi @odoo/payroll-doc-review! This PR is ready for your review. Thanks in advance!

**Review by auva-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
