### PR TITLE
[REF] social marketing: doc restructure

### PR DESCRIPTION
**Pull request by ksc-odoo**
As part of my continued effort to make all the marketing doc pages look streamlined and uniform, I am giving this **entire** Social Marketing scope of docs a "face lift"

This specific PR will be the first of a series...
This initial PR will place the basic information on the 'Social Marketing' link itself, remove the 'Essentials', rework the toctree to accommodate the various sections (as opposed to having them all on one, super-long page)

The *current* content for those other sections will remain as-is *for now*, as placeholders, and subsequent PRs will be created to update those sections (updated content, screenshots, formatting, etc.) in the **very near** future...

PROJECT TASK: https://www.odoo.com/odoo/project/3835/tasks/4056985?cids=3

### CODE REVIEW

**Comment by ksc-odoo** [comment]
Since this is a mainly a "technical-based" PR, I think tagging you, @samueljlieber straight-away would be the best move. So, if you agree, would you mind giving this a Peer/Tech review? Then, once you approve (and we get this merged), I can work on updating the subsequent sections of this scope. Thanks! 👍

**Review by StraubCreative — CHANGES_REQUESTED** [review]
Missing 301 redirect(s) for deleted RST files
Screenshot 2024-07-22 at 4 47 11 PM

**Comment by ksc-odoo** [comment]
Great catch, @StraubCreative -- I have gone back and added the necessary redirect info to the 17.0 txt file, and believe this is now ready for another look from you (whenever you get a chance). Thanks! 🙏

**Comment by ksc-odoo** [comment]
hey @samueljlieber -- think this one is ready for another look, whenever you get a chance. Thanks!

**Pull request closed without merging**
