### PR TITLE
[IMP]l10n_es: Tax report: Modelo 130

### PR DESCRIPTION
**Pull request by igbe-odoo**
Add the modelo 130 report and the corresponding BOE files export for spain localization.

Add also some documentation for using the report.

task-3866238

### CODE REVIEW

**Comment by toaa-odoo** [comment]
Hi @igbe-odoo! Thanks for your great work. I pushed some changes to comply with [documentation guidelines](https://www.odoo.com/documentation/16.0/contributing/documentation/content_guidelines.html) and removed some screenshots that were not necessary.

@odoo/be-doc-review From what I can tell, the R&D task has been not merged yet. Might be best to give r+ rights.

**Review by auva-odoo — APPROVED** [review]
Hi @igbe-odoo thank you for updating the doc :slightly_smiling_face: I also pushed some minor changes (to correct a typo and the formatting mainly). You can r+ whenever you're ready. Thanks again!
@robodoo delegate+

**Comment by auva-odoo** [comment]
Hey @igbe-odoo, I noticed that the (formatting) changes I pushed while reviewing this PR were overwritten and reverted. Just wanted to check in and see if there was a specific reason for that? Thanks!

**Comment by malb-odoo** [comment]
i presume he forgot to pull the branch before force pushing on it :grimacing:

**Comment by igbe-odoo** [comment]
Indeed I made a little mistake while rebasing my branche I'm sorry about that I didn't see it, I will cherry pick your commit and reset the branch in the state she was before. Thanks you for noticing me the issue and please excuse my little mistake, mb on this :/

**Comment by auva-odoo** [comment]
No worries at all, it happens! :slightly_smiling_face:

**Comment by igbe-odoo** [comment]
It should be good now 😉

**Comment by malb-odoo** [comment]
Don't know if the delegate still works with the different force push, can we have a new delegate :smile:

**Review by auva-odoo — APPROVED** [review]
Sorry for the delay guys, for some reason I wasn't notified.
Anyways, @robodoo delegate+

**Comment by william-andre** [comment]
@igbe-odoo You have the delegated rights, so you have to r+ this one

**Comment by igbe-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
