### PR TITLE
[16.0] Add RO

### PR DESCRIPTION
**Pull request by dhongu**

### CODE REVIEW

**Review by AntoineVDV — COMMENTED** [review]
Hello @dhongu, translations are managed on transifex.com, and there is currently no translation available for the documentation. Therefore, there is no point in making RO available in the languages switcher.

**Comment by dhongu** [comment]
II am interested in contributing to the Odoo community by translating the documentation into Romanian. I initially thought that I needed to create a Pull Request on GitHub to add the Romanian language, but I have also requested that the Romanian language be added on the Transifex website.

Could you please provide me with the necessary information and guidelines for this task? I would appreciate any resources or recommendations you can provide to make the translation process as smooth as possible.

**Comment by AntoineVDV** [comment]
> II am interested in contributing to the Odoo community by translating the documentation into Romanian. I initially thought that I needed to create a Pull Request on GitHub to add the Romanian language, but I have also requested that the Romanian language be added on the Transifex website.
> 
> Could you please provide me with the necessary information and guidelines for this task? I would appreciate any resources or recommendations you can provide to make the translation process as smooth as possible.

Until we add a proper guide for the translations to our [contributing to Odoo](https://www.odoo.com/documentation/master/contributing.html) documentation, I suggest reading our [wiki page](https://github.com/odoo/odoo/wiki/Translations). 

Regarding your request to open translations to RO, I will let @mart-e answer you ;)

**Comment by mart-e** [comment]
Hello,

Odoo 16.0 is translated at 64% in Romanian. This is not bad but it would be good to improve this first before adding the language on other projects like the documentation.
If you suceed to grab another 10% of translations at https://www.transifex.com/odoo/odoo-16/language/ro/ , I can add the language on the documentation https://www.transifex.com/odoo/odoo-16-doc/

**Comment by dhongu** [comment]
We are happy to report that our team at Terrabit has mobilized to translate Odoo 16.0 into Romanian, and we have achieved a translation percentage of 75%. We will continue to work on the translation and aim to improve upon this progress.

We believe that the level of translation achieved so far is sufficient to move forward with adding Romanian as a language for the Odoo documentation on Transifex.

**Comment by mart-e** [comment]
@dhongu great job in only 3 days ! I have added the language on Transifex
https://www.transifex.com/odoo/odoo-16-doc/language/ro/

At the moment it's not published on https://www.odoo.com/documentation/16.0/ yet but as soon as you have made some progress there, don't hesitate to ping me again and I will publish it

**Comment by dhongu** [comment]
I just wanted to express my gratitude for granting me access to the translated Odoo documentation for version 16.0. 

I was wondering if it would be possible to also receive access to the translated documentation for versions 14.0 and 15.0. Many of my clients are still using these versions and I believe having access to the translated documentation would be very helpful in supporting them.

Thank you in advance for considering my request.

**Pull request closed without merging**
