### PR TITLE
[FIX] MRP: Update using work centers for 15.0

### PR DESCRIPTION
**Pull request by hojo-odoo**
This PR updates the Manage work orders using work centers doc for 15.0. This SHOULD NOT be forward-ported to 16.0.

### CODE REVIEW

**Comment by hojo-odoo** [comment]
Hey @StraubCreative,

This is ready for review. 

Thanks,
hojo

**Review by samueljlieber — CHANGES_REQUESTED** [review]
Hi @hojo-odoo 👋 great job on this doc. The only two technical changes I had to make was to update the image filenames to not use underscores and italicize Odoo Manufacturing app where applicable.

Media file naming convention: https://www.odoo.com/documentation/16.0/contributing/documentation/content_guidelines.html#media-files

I will approve these changes right now and commit them, then tag this PR for final review.

**Review by samueljlieber — APPROVED** [review]

**Comment by samueljlieber** [comment]
Implemented and approved technical changes in https://github.com/odoo/documentation/commit/acd7a9725db18a8961c47cb54d4ef7494b88f21a. 🙂

@StraubCreative ready for final review - I would like to reiterate @hojo-odoo 's [comment](https://github.com/odoo/documentation/pull/3776#issue-1615851191) that PR is for 15.0 only and should not be forward ported.

**Comment by StraubCreative** [comment]
[28e216f](https://github.com/odoo/documentation/pull/3776/commits/28e216f73a7f7ca9bc8ccf34001dc4d1afc0b78b)
- *Odoo Manufacturing* --> Odoo *Manufacturing* (only the app name gets italicized)

Everything else LGTM. All checks pass ✅ 

@robodoo r+
@fw-bot ignore

**Review by StraubCreative — APPROVED** [review]

**Pull request closed without merging**
