### PR TITLE
[IMP] point_of_sale: add Adyen details

### PR DESCRIPTION
**Pull request by Ysoroko**
This PR adds a link to a much needed Adyen coverage per country and their terminal models

task-3865904

### CODE REVIEW

**Review by LoredanaLrpz — APPROVED** [review]

**Comment by jcs-odoo** [comment]
@robodoo r+

**Comment by jcs-odoo** [comment]
@robodoo r-

**Comment by jcs-odoo** [comment]
@robodoo r+

**Comment by jcs-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
