### PR TITLE
[IMP] inventory: add a note on default warehouses

### PR DESCRIPTION
**Pull request by svirmasalo**

### CODE REVIEW

**Review by brse-odoo — APPROVED** [review]
Hi @svirmasalo, this change of an additional note looks good! It's definitely useful to know that 
a) salespeople can have default warehouses set, and 
b) doing so will set their default warehouse on sales orders, making the process much easier.

**Comment by brse-odoo** [comment]
Hi @StraubCreative, this PR is ready for your review. Thanks!

**Review by StraubCreative — APPROVED** [review]
Thanks for the added context @svirmasalo.

Approving for quick merge and then @brse-odoo we'll need to clean up the content + RST formatting asap in another PR. The doc is very out of date 😅 

@odoo/doc-review can you conditionally approve so we can take the added content here into a new PR that's within Odoo's repo (and not a fork?).

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

**Comment by AntoineVDV** [comment]
@robodoo squash

**Comment by AntoineVDV** [comment]
@brse-odoo If you rewrite that page, I think this note should instead be a tip.

**Comment by AntoineVDV** [comment]
@robodoo r-

Reason: breaking the mergebot

**Comment by AntoineVDV** [comment]
@StraubCreative @brse-odoo The CI checks on this PR were too old and failed to detect a problem in the diff. I rebuild them, and they're now red as they should. Could you please fix the issue and push on this PR's branch?

**Comment by StraubCreative** [comment]
Cleaned up the RST, reformatted the `note` to a `tip`, checks pass as of
[b97b237](https://github.com/odoo/documentation/pull/2979/commits/b97b237cf0be53a1b1f7f45a2ace8d84d7f3268b) 👍

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
