### PR TITLE
[REM] accounting: removing none existing module

### PR DESCRIPTION
**Pull request by Abridbus**
The module ' l10n_fr_certification ' has been integrate in the account module.
so this is not installable anymore. Removed this but kept the explanation
for the POS.
opw-2389435

### CODE REVIEW

**Comment by Abridbus** [comment]
Adding second commit to explain the re sequencing for french customer.

As discussed with @tsb-odoo

**Comment by Abridbus** [comment]
@alt-odoo 
If you can merge :D

**Comment by alt-odoo** [comment]
I'm OK with the first commit, but for the resequence commit I'm not sure it should be put only in french localization as it concerns a generic feature...

@jcs-odoo I believe you are actively working on maintaining the doc, you might have a good opinion on this too :)

**Comment by jcs-odoo** [comment]
I agree that if it is not restricted to a certain localization, it should be in the general documentation or Odoo Learn.

Now, I read that this situation is particularly problematic for French users, but I'm not sure to see why.
Are the restrictions written here limited to french companies -as the title of the commit suggests-, or is it standard for all countries?

Cheers,
Jonathan

**Comment by jcs-odoo** [comment]
New Pull Request #940

**Comment by jcs-odoo** [comment]
@Abridbus can I delete the branch `13.0-l10n_fr-remove-not-existing-module`?

**Pull request closed without merging**
