### PR TITLE
[REM] finance: Taxcloud documentation

### PR DESCRIPTION
**Pull request by kekiss**
Removed references to Taxcloud because Taxcloud will no longer be available starting in Odoo 17.2.

https://www.odoo.com/odoo/project.task/4118773

### CODE REVIEW

**Comment by kekiss** [comment]
Hi @ksc-odoo !

Felicia said to tag you for review in order to expedite this PR, because Zac said he'd like this merged by EOD Friday 8/16/24!

**Review by ksc-odoo — APPROVED** [review]
Hey there @kekiss -- just finished my Final Review of this super quick PR. Looks like you adequately removed all the Taxcloud information, and believe this one is now ready for a Tech Review from Sam! Feel free to tag him whenever you get a chance. Thanks!

**Comment by kekiss** [comment]
@samueljlieber tagging you for tech review! Zac said he'd like this merged by EOD today (8/16/24)

**Review by samueljlieber — APPROVED** [review]
Nice one @kekiss! Your changes in this PR look good to me! 
Thank you for your work!
..
@robodoo r+

**Pull request closed without merging**
