### PR TITLE
[IMP] legal/terms: update spanish ToC docs

### PR DESCRIPTION
**Pull request by StraubCreative**
**Overview**
This PR updates the Spanish(ES) content inside legal/terms.

**Files updated**
- `enterprise_es.rst`
- `partnership_es` 

**New file**
- `terms_of_sale_es.rst`

**Misc**
Updated formatting for consistent line length in RST files.
Removed trailing white spaces between line breaks.

### CODE REVIEW

**Comment by jcs-odoo** [comment]
Hello @StraubCreative .

I believe this PR has the same purpose as this old PR #939 .
Cécile Collart asked me to keep that version as it was triple-quadruple checked already from a legal pov.

cc @odony

**Comment by jubodoo** [comment]
> Hello @StraubCreative .
> 
> I believe this PR has the same purpose as this old PR #939 . Cécile Collart asked me to keep that version as it was triple-quadruple checked already from a legal pov.
> 
> cc @odony

The same purpose but it's been better updated (in theory). There's just a small issue about the company name I asked Zach to fix (translators put MX company name) I think this should be the correct one. The other one I think wasn't pushed because there were mistakes IIRC.

**Comment by jubodoo** [comment]
Oh and @jcs-odoo This one has also more content (term of sales) so we either need to add that separately or do something about it.

**Comment by jcs-odoo** [comment]
> IIRC

Hello @jubodoo and @StraubCreative !
Sorry, I didn't look into it in detail. Indeed, it also translates the partnership agreement and terms of sales :)

I see that #939 (with the Odoo Enterprise Agreement) has been merged, now. Olivier was simply too busy to review it before, as he told me last month. Nothing to do with the content itself, it seems.

If I understood correctly, these changes are version-related so it's already targeting 15.0 and not the versions before (which is correct).

So you'll have to rebase your branch and fix the conflicts first to be able to merge this pr and add the partnership agreement and the tos. (but probably not the enterprise agreement anymore, then)

Content-wise, I leave that to the legal and translation teams.
But maybe check with @odoo/legal and (cco) first? I'm afraid I can't help much more.

Cheers :)

**Comment by StraubCreative** [comment]
> So you'll have to rebase your branch and fix the conflicts first to be able to merge this pr and add the partnership agreement and the tos. (but probably not the enterprise agreement anymore, then)

Sweet 👍

Next steps when I rebase the branch, so I understand: 
- allow the incoming changes from `enterprise.rst` and `legal.rst` to overwrite what we have to keep the integrity of approved changes in #939
- layer our changes for `partnership_es.rst`, `terms_of_sale_es.rst`, and `terms_of_sale_tex_es.rst` on top.

This way we backpack #939 into a fully updated version with all 3 legal docs for Spanish.

Will get on it as soon as I can. Thank you for your help! 😎 

cc: @jubodoo

**Comment by jubodoo** [comment]
> Cheers :)

So we'll just rebase & use this for the 2 other ones I guess? (let's keep in mind these doc have no legal values but still the translators checked with the MX office lawyers, so I would assume they are correctly translated)

**Comment by StraubCreative** [comment]
Closing this since it's been open for so long without resolution and we would need to edit more updated content instead of what's on the feature branch.

Can create new PR if necessary please advise if that's the case @jubodoo

**Pull request closed without merging**
