### PR TITLE
Clarify documentation of routes

### PR DESCRIPTION
**Pull request by mdb-odoo**
Starting at line 259 - updated the text. This text was a mix of incorrect and confusing statements. I changed some words and sentences to correct the text and make it make more sense. Also updated the rule name to Pull & Push as that is what it is called in Odoo.

### CODE REVIEW

**Comment by jcs-odoo** [comment]
@Lau-Odoo 
I believe this is for you. Also, it could be based on 13.0 but I don't think mdb can do this change directly since it looks like a patch made directly on GitHub.

Cheers :)

**Comment by AntoineVDV** [comment]
> it could be based on 13.0 but I don't think mdb can do this change directly since it looks like a patch made directly on GitHub.

Then it's best to close this PR and open a new one targeting the appropriate branch. cc @mdb-odoo

**Comment by mdb-odoo** [comment]
@AntoineVDV The documentation for the mentioned page is the same for V13 and V14, both incorrect.

**Comment by AntoineVDV** [comment]
> @AntoineVDV The documentation for the mentioned page is the same for V13 and V14, both incorrect.

Alright, do you create the PR for 13.0 then?

**Comment by mdb-odoo** [comment]
@AntoineVDV I will. This was my first time doing this so I wasn't sure on the full protocol

**Comment by AntoineVDV** [comment]
> @AntoineVDV I will. This was my first time doing this so I wasn't sure on the full protocol

If you know Git, it might be easier for you to create a branch on this repository. See https://www.odoo.com/documentation/master/contributing/documentation/introduction_guide.html#use-the-canonical-git-workflow.

I close this PR as you will open another one.

**Pull request closed without merging**
