### PR TITLE
[FIX] config: werkzeug 1.0.x docs are no longer online

### PR DESCRIPTION
**Pull request by aj-fuentes**
```
❯ curl -sw '%{http_code}\n' -o /dev/null https://werkzeug.palletsprojects.com/en/1.0.x/
404

❯ curl -sw '%{http_code}\n' -o /dev/null https://werkzeug.palletsprojects.com/en/2.0.x/
200
```

### CODE REVIEW

**Comment by aj-fuentes** [comment]
@fw-bot ignore

**Comment by KangOl** [comment]
What about linking to the archived url?
https://web.archive.org/web/20230308050341/https://werkzeug.palletsprojects.com/en/1.0.x/

**Comment by aj-fuentes** [comment]
@KangOl 
> What about linking to the archived url?
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://web.archive.org/web/20230308050341/https://werkzeug.palletsprojects.com/en/1.0.x/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: NOT FOUND for url: https://web.archive.org/web/20230308050341/https://werkzeug.palletsprojects.com/en/1.0.x/objects.inv
```
And there is [nothing](https://web.archive.org/web/20230000000000*/https://werkzeug.palletsprojects.com/en/1.0.x/objects.inv) archived for `1.0.x/objects.inv`.

**Comment by aj-fuentes** [comment]
@AntoineVDV this is to support PRs for older versions. Although unsupported it's important for upgrades.

**Comment by AntoineVDV** [comment]
Ok then

@robodoo r+
@fw-bot ignore

**Pull request closed without merging**
