### PR TITLE
[ADD] conf: add sitemap generation

### PR DESCRIPTION
**Pull request by mart-e**
Requires jdillard/sphinx-sitemap@6d5e7b4aeb0a9

Replaces #499

Xavier is working to add parallelism at jdillard/sphinx-sitemap#29

### CODE REVIEW

**Comment by mart-e** [comment]
Example of sitemap.xml file generated (manually indented)
https://gist.github.com/mart-e/27a51ff3de495af3a7fd6d2a5edabf8c

**Comment by xmo-odoo** [comment]
So this is going to build one sitemap file per version per language right?

**Comment by mart-e** [comment]
> So this is going to build one sitemap file per version per language right?

Yes, same as for the actual content, we call `sphinx-build` for each version/language combo.

> Is it really useful to use the "localized" URLs then? Why not just format the root URL ourselves and pass that directly to sphinx-sitemap?

Would that be better? Because the code is pretty simple now :)

**Comment by xmo-odoo** [comment]
>> So this is going to build one sitemap file per version per language right?
> 
> Yes, same as for the actual content, we call sphinx-build for each version/language combo.

Right so the "overlord" process managing the generation pipeline will then be generating the "index" sitemap?

Also how do we hook *that* into `odoo.com`'s sitemap? Is it possible to link an index to an index? Or to have multiple "root" sitemaps not linked through indexes?

> > Is it really useful to use the "localized" URLs then? Why not just format the root URL ourselves and pass that directly to sphinx-sitemap?
> 
> Would that be better? Because the code is pretty simple now :)

Dunno, asking. We're already having to conditionally dispatch based on the reference language...

**Comment by Xavier-Do** [comment]
I summon @robodoo

**Comment by Xavier-Do** [comment]
I summon @robodoo

**Comment by xmo-odoo** [comment]
@robodoo ping

**Comment by Xavier-Do** [comment]
@robodoo ping

**Comment by mart-e** [comment]
Closing as not useful. All pages are accessible through the homepage of the doc and are already properly indexed by Google.

**Pull request closed without merging**
