### PR TITLE
[IMP] general: iot add payment terminals link

### PR DESCRIPTION
**Pull request by lse-odoo**

### CODE REVIEW

**Comment by lse-odoo** [comment]
(note: need to update documentation link in 16 to add SIX)

**Review by tiku-odoo — APPROVED** [review]
@lse-odoo 

I made some small changes, I am going to pass this PR along to merge. 

Thanks for this change. 

:+1: 

Tim

**Comment by tiku-odoo** [comment]
@StraubCreative 

This PR is ready for your merge when you have a moment. Just a small change, making the toc tree visible for iot devices and adding two see also links (to payment terminals). 

Thanks for your review. 

Tim :+1:

**Review by StraubCreative — APPROVED** [review]
Seems good, thanks @lse-odoo @tiku-odoo 
..
@robodoo r+

**Pull request closed without merging**
