### PR TITLE
[ADD] l10n_in_reports_gstr: added documentation for Indian GST service

### PR DESCRIPTION
**Pull request by hapa-odoo**
==========
In this commit, I have added documentation for GST return filing. I have explained how to Enable API 
Access on GST Portal, a configuration in odoo. I have also explained different GSTR reports.

### CODE REVIEW

**Comment by jva-odoo** [comment]
@jco-odoo @jcs-odoo

**Review by jcs-odoo — COMMENTED** [review]
some notes but I'll update the commit and backport the common content to 15.0

This PR should have been split in two commits:
- one to update the current content, since it needs to be applied from 15.0
- one for the GST addition, since it targets 16.0

**Review by jcs-odoo — APPROVED** [review]
@robodoo r+

**Comment by jva-odoo** [comment]
@jcs-odoo Thank you :)

**Pull request closed without merging**
