### PR TITLE
[IMP] sales: updated quotation template for 17

### PR DESCRIPTION
**Pull request by ksc-odoo**
PROJECT TASK: https://www.odoo.com/web#id=3649265&cids=3&model=project.task&view_type=form

### CODE REVIEW

**Comment by ksc-odoo** [comment]
Alrighty, @meng-odoo ... this is ready for its first round of Peer Review, whenever you get a chance!

**Review by jero-odoo — APPROVED** [review]
Hey @ksc-odoo , great job on this doc! Approving and sending it along to @samueljlieber for tech/review!

**Review by samueljlieber — APPROVED** [review]
Looks great @ksc-odoo, nice job! I am approving now, but will push up a commit to shorten the commit message 👍

**Comment by samueljlieber** [comment]
@StraubCreative this PR is good to go 👍

**Comment by StraubCreative** [comment]
@robodoo r+

**Review by StraubCreative — APPROVED** [review]

**Pull request closed without merging**
