### PR TITLE
[IMP] finance/accounting: add Delivery Guide to CL localization

### PR DESCRIPTION
**Pull request by StraubCreative**
_Following up from #1907:_

Hi @chiaraprattico :wave:

Thank you for your recent review (now on the closed pull request linked above).

I created this new PR to resolve the rebase/merge conflict between `15.0` vs. `14.0` base branches. 

Per your [review starting here](https://github.com/odoo/documentation/pull/1907#discussion_r866580794) on the old PR, I performed change requests and a few extra things as follows:

- reformatted all lines that required a line break at/before 100th character or where line was broken too early.
- removed all trailing whitespaces
- removed all unnecessary double spaces found t/o the body content
- resized all newly added images to HD res to ~1280px or less
- added `:guilabel:` directive where appropriate in the _new content only_. Please [see comment here](https://github.com/odoo/documentation/pull/1907#discussion_r874252096) on old PR and lmk what you’d like to do.
- added `:menuselection:` directive where appropriate (instead of using `**bold**` formatting)

Please advise as to further changes that need to be made, if any.

Thank you kindly :)

### CODE REVIEW

**Comment by jcs-odoo** [comment]
Hello @StraubCreative and @chiaraprattico 

Quick comments here :)
It's not that the images have to be max 1280px in width, it's just that if you take them on a 4K screen, you resize them to 50%.
Here, most of them are still way too wide for what they represent (e.g. chile45). Also, the edges on the images seem a bit weird, is it due to compression? I'm curious how you take,  resize and compress your screenshots ^^

As for the rebase, thanks to a recommendation from martin, we have a way to change the target and base of a PR without having to close a PR and reopen a new one:
- put the PR in draft mode
- change the PR's target
- change the base of your branch + force push
- reopen the PR for review

This way, no code owner is pinged.

Have a great one :)

**Comment by chiaraprattico** [comment]
Thanks @StraubCreative, :guilabel: for the new content is great, looks fine otherwise. :)

**Comment by StraubCreative** [comment]
> Quick comments here :) It's not that the images have to be max 1280px in width, it's just that if you take them on a 4K screen, you resize them to 50%. Here, most of them are still way too wide for what they represent (e.g. chile45). Also, the edges on the images seem a bit weird, is it due to compression? I'm curious how you take, resize and compress your screenshots ^^

Yes could be due to compression. A few of the images I resized _after_ they were compressed so the resampling could explain why some look weird. We can redo images that could use a better crop or appear weird. @fvz-odoo will connect with you on this.

> As for the rebase, thanks to a recommendation from martin, we have a way to change the target and base of a PR without having to close a PR and reopen a new one:
> 
>     * put the PR in draft mode
> 
>     * change the PR's target
> 
>     * change the base of your branch + force push
> 
>     * reopen the PR for review
> 

Yes I wanted to do this! Good to know how the whole thing works. Thanks for letting me know.

In this case I couldn't just change the base branch locally without getting hit with a bajillion merge conflicts. So I started fresh on 14.0 base branch and `git cherry-pick`'d the commit from the old branch with 15.0 as its base. 

So I'm clear...are you saying there's a way to get around this?

**Comment by StraubCreative** [comment]
@jcs-odoo replaced all of the images with more zoomed in screenshots, conservative crops, + HD resolution. 
Much better now I think :)

@chiaraprattico if content review is good to go please approve to next stage for DR :)

Thank you both!

**Review by chiaraprattico — APPROVED** [review]

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Hello, this PR's images need to be moved to the appropriate folder following https://github.com/odoo/documentation/pull/2006
It appears that it also has a conflict with 14.0. I expect the conflict to be due to an `image` directive so I advise that you move the images first, push, and see if the conflict is still there. If it is, run `git rebase 14.0` and fix the conflict ;)

**Comment by samueljlieber** [comment]
Hi @AntoineVDV!
I moved the images out of the media directive and fixed the conflict, which was due to the `image` directive 😁

Thanks!

**Review by AntoineVDV — APPROVED** [review]
> Hi @AntoineVDV!
I moved the images out of the media directive and fixed the conflict, which was due to the image directive grin
> 
> Thanks!

:ok_hand: 

@robodoo r+

**Pull request closed without merging**
