### PR TITLE
[FIX] general: ir.config_parameter correction

### PR DESCRIPTION
**Pull request by sarmad90**
Fix the incorrect usage of `ir.config.parameters`. The correct one is `ir.config_parameter` which can be seen sprinkled throughout the codebase.

### CODE REVIEW

**Review by ksc-odoo — APPROVED** [review]
@sarmad90 -- thanks for catching this. your change looks good to me. approving now. thanks again 🙏

**Comment by sarmad90** [comment]
@ksbh-odoo who's gonna merge it?

**Comment by ksbh-odoo** [comment]
> @ksbh-odoo who's gonna merge it?

I think he ment @ksc-odoo

**Review by samueljlieber — CHANGES_REQUESTED** [review]
Hi @sarmad90, thank you for the quick fix with this PR! I am requesting just a small change to correct the commit message to follow the [commit convention](https://github.com/odoo/documentation/blob/17.0/commit_template.txt):

```
[FIX] general: ir.config_parameter correction
```
After this change is made, this PR looks good to me to merge 👍

**Review by samueljlieber — APPROVED** [review]
Hi @sarmad90, I went ahead and updated the commit message and will merge shortly. Thanks again for the contribution 🙂

**Comment by samueljlieber** [comment]
@robodoo r+

**Pull request closed without merging**
