### PR TITLE
[MOV] Misc: Move Portal doc to Misc

### PR DESCRIPTION
**Pull request by tiku-odoo**
Moved Portal user doc from advanced Sales to Misc >> Users and Companies. 

@StraubCreative This PR is ready for your final review 👍

### CODE REVIEW

**Comment by StraubCreative** [comment]
Fixed merge conflict on [c050a89](https://github.com/odoo/documentation/pull/3457/commits/c050a8958e77cf4e36db69e6042df20ac477ab0f).

**Review by StraubCreative — APPROVED** [review]
LGTM @tiku-odoo. 
Passing to @odoo/doc-review  🚀

**Comment by StraubCreative** [comment]
@odoo/doc-review 
QQ: Since the file move applies to all versions, we'll want to add the redirects to `15.0.txt` and 16.0.txt` on the forward-port PRs, right? Or is that not needed?

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+

@StraubCreative For a given version (say 16.0), the rules of all redirects/XY.txt files apply. Therefore, there is no need to propagate the new redirect rule to other files ;)

**Pull request closed without merging**
