### PR TITLE
[FIX] developer/javascript_cheatsheet: fix a typo

### PR DESCRIPTION
**Pull request by NiranjanAbhyankar**
Changed '... an odoo developers ...' to '... an odoo developer ...'

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]
Hi, @NiranjanAbhyankar thanks for your fix!

@robodoo r+ squash

**Comment by AntoineVDV** [comment]
@robodoo retry

**Comment by xmo-odoo** [comment]
@robodoo retry

**Comment by AntoineVDV** [comment]
@robodoo retry

**Comment by AntoineVDV** [comment]
@robodoo r+

**Pull request closed without merging**
