### PR TITLE
[ADD] Quality: Take a Picture Check

### PR DESCRIPTION
**Pull request by hojo-odoo**
This PR adds a new doc detailing how to create and process Take a Picture quality checks.

NOTE: One of the checks is failing because the PR contains a reference to the "Quality checks" doc, which is not yet live. That doc should be live before this one, at which point the ref tags in this doc will work as intended.

### CODE REVIEW

**Comment by StraubCreative** [comment]
@odoo/us-doc-review 
Need #6454 to merge first, which includes the necessary toctree updates for the CI checks to pass

**Review by samueljlieber — APPROVED** [review]
Hi @hojo-odoo awesome job with this PR! I am approving now and pushing up a commit to resolve the merge conflict. Thank you!

**Comment by samueljlieber** [comment]
Hi @StraubCreative this PR is ready to go!

**Review by StraubCreative — APPROVED** [review]
Same here @hojo-odoo we'll want to correct references to Tablet View starting at `saas-16.4` branch, onwards.

Otherwise this concludes the Quality series of docs, nice work 🙂 

@robodoo r+

**Comment by StraubCreative** [comment]
@robodoo r+

**Pull request closed without merging**
