### PR TITLE
[IMP] dev/*: remove unnecessary fields from view samples

### PR DESCRIPTION
**Pull request by Gorash**
related to https://github.com/odoo/odoo/pull/137031

### CODE REVIEW

**Comment by AntoineVDV** [comment]
@Feyensv Even if the odoo PR is not ready, the documentation PR is unlikely to change further.

@robodoo delegate+

**Comment by Feyensv** [comment]
@robodoo squash

**Comment by AntoineVDV** [comment]
@robodoo r+ delegate=rco-odoo

**Comment by rco-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
