### PR TITLE
[IMP] Maintain/Productivity: Azure Name Change

### PR DESCRIPTION
**Pull request by tiku-odoo**
Doc task:  https://www.odoo.com/web#model=project.task&id=3551779&active_id=3551779&cids=3

### CODE REVIEW

**Comment by tiku-odoo** [comment]
@samueljlieber This doc is ready for your review...

Microsoft Azure Active Directory (Azure AD) is being renamed to Microsoft Entra ID

Thanks in advance for your review. 

:+1:  Tim

**Review by samueljlieber — APPROVED** [review]
Hi @tiku-odoo these changes look good to me! Please update the commit message and PR title to follow the [convention](https://github.com/odoo/documentation/blob/14.0/commit_template.txt) before passing to @StraubCreative 🙂

**Comment by tiku-odoo** [comment]
@StraubCreative

This name change-edit PR is ready for your review. 

Thanks. 
Tim :+1:

**Review by StraubCreative — APPROVED** [review]
Looks good, thanks @tiku-odoo 👍 

@robodoo r+

**Pull request closed without merging**
