### PR TITLE
[IMP] l10n_ar: Add eCommerce Webinar

### PR DESCRIPTION
**Pull request by vbe-odoo**
Add a link to the latest webinar for ARG related to eCommerce

### CODE REVIEW

**Comment by vbe-odoo** [comment]
Hi @jcs-odoo I hope you are doing well 😄 
I want to add a new webinar that we have for ARG related to eCommerce.
Could you help me with this?

Thanks!
Bests!
@ren-odoo

**Comment by jcs-odoo** [comment]
> Hi @jcs-odoo I hope you are doing well 😄
> I want to add a new webinar that we have for ARG related to eCommerce.
> Could you help me with this?
> 
> Thanks!
> Bests!
> @ren-odoo

Sure. I'll adapt the commit since the deployment of the new doc implies that all current Pull Requests have conflicts.

Just to be sure, the new video is for v14 only, right?

**Review by Feyensv — APPROVED** [review]

**Comment by Feyensv** [comment]
> Just to be sure, the new video is for v14 only, right?

Waiting for @vbe-odoo confirmation to be sure this shouldn't target 13 then ;).

**Comment by vbe-odoo** [comment]
Hi there! Thanks for the updates!
Yes, this is only for V14, this is not a feature available in previous versions, will be V14 and future versions.
Thanks!
cc' @jcs-odoo @Feyensv

**Pull request merged**
