### PR TITLE
[IMP] accounting: l10n_mx content updates

### PR DESCRIPTION
**Pull request by samueljlieber**
This PR improves the Mexico l10n documentation, authored by @feav-odoo [original commit on fork](https://github.com/mx-support-bugfix/documentation/commit/6704d2c1a87871bfae0471dd81ba9fe3d6cf3802):
> Adaptation of l10n_mx Documentation, adapting it to include CFDI 4.0, Delivery Guide, Polizas, and much more.

This PR can be FWP to 16.0, another PR will be opened for 16.0 specific edits

### CODE REVIEW

**Comment by samueljlieber** [comment]
Hi @feav-odoo 👋
Great job with writing up the RST for the improvements to this doc! I opened this pull request because I wasnt able to do so on your fork with it being an already merged commit.

Please find the **Commits** tab at the top of this PR, here you will see two commits. The first one is [your original changes](https://github.com/odoo/documentation/pull/5225/commits/bff45c2d9c5170c495dc256fd27adf758274cc0f) and the second is a commit containing [my technical changes](https://github.com/odoo/documentation/pull/5225/commits/ac875cd98ca4aa69a2fc53207dca0b5be54662fb).

I opened this PR as a draft since there are a couple more items to fix that I need your help with, but overall really great job with the RST syntax!

## Below is a summary of some of the technical changes I made

- Heading delimiters need to be the same character length as the heading's text - [guidelines](https://www.odoo.com/documentation/master/contributing/documentation/rst_cheat_sheet.html#headings), and should be sentence case rather than title case - [guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html#titles-and-headings):
  ```
  Modules installation
  -------------------- ✅
  
  Modules Installation
  ----------------------- ❌
  ```
- Use the **:guilabel:\`Tag\`** on text that is present on the screen (user interface) in the active instruction - [guidelines](https://www.odoo.com/documentation/master/contributing/documentation/rst_cheat_sheet.html#gui-element):
  ```
  ...by clicking the :guilabel:`Send and Print` button. ✅

  ...by clicking the *Send and Print* button. ❌
  ```
- Image files should use hyphens rather than underscores for filenames, be compressed with a tool such as [PNGquant](https://pngquant.org/), only shows what is needed (no need to show the entire interface), and be no more than 933px wide - [guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html#images)
- Lines should break at 100 characters of length - [guidelines](https://www.odoo.com/documentation/master/contributing/documentation/rst_guidelines.html#start-a-new-line-before-the-100th-character)

## And the following I need your help with

Throughout the doc there are duplicate `:alt:` tags on images. Each image should have a unique `:alt:` tag that provide a good short description of the image ([guidelines](https://www.odoo.com/documentation/master/contributing/documentation/content_guidelines.html#alt-tags)).

Can you please make changes as *Suggestions* in the **Files Changed** tab for each duplicate or non-descriptive `:alt:` tag? 🙏

Secondly, a handful of screenshots are showing a large amount of the UI when the main focus is only a small portion of the UI, can you please re-take or crop these images? 🙏

Lastly, can you please confirm or deny that the of content in this PR is applicable to 15.0 and 16.0? You will be able to make 16.0 specific edits on a forward port of this PR 🙂

Please let me know if you have any questions with making these changes, or anything else! Thank you!☀️

**Comment by samueljlieber** [comment]
Resized and cropped many of the images and removed a few that felt unnecessary in https://github.com/odoo/documentation/commit/979472688bad4f344f5249b2c5e1e8f81ec99086 and https://github.com/odoo/documentation/commit/241618366d1185e6fef09f2b80b002364d3c96ab.

**Comment by samueljlieber** [comment]
Finalized image changes with the help of @feav-odoo. Opening this PR up from draft for review 🙂

**Review by toaa-odoo — CHANGES_REQUESTED** [review]
Hi, thanks for your work! This was a really long one to review.

Overall only small modifications, although I did remove some screenshots that were superfluous (what was shown was clear enough or basic enough from text alone). This lightens the page.

I'll let you see if any changes are wrong or unnecessary :)

**Review by toaa-odoo — APPROVED** [review]

**Review by xpl-odoo — COMMENTED** [review]
Hi @samueljlieber!
Are you looking for an in-depth review here? The file is _long_, and I would have several suggestions to make (e.g., my previous comments on the CL/CO localizations). However, I assume you didn't go for a full rewrite to follow our guidelines strictly.
As a quick example, I know the US team avoids using the _you_ (unless this changed recently?), and obviously, it's not the case in this PR.
As it isn't part of the documentation guidelines (except for headings), it's fine, but it makes me wonder what you are looking for/what's the purpose of the update?

**Comment by samueljlieber** [comment]
Hi @xpl-odoo, the content in this PR is authored by @feav-odoo with the purpose to revise all of the main workflows for l10n_mx. I opened this PR for him because the improvements were not on the right base branch on his [fork](https://github.com/mx-support-bugfix/documentation/commit/6704d2c1a87871bfae0471dd81ba9fe3d6cf3802). 

I just pushed a [second commit](https://github.com/odoo/documentation/pull/5225/commits/7cda9375164c6879303be0474bcb78f0d037204f) for @feav-odoo and I improve the content based on your comment. We will tag you for review once we feel this PR is ready for another look 🙂

**Comment by lao-odoo** [comment]
@xpl-odoo Hi, here from the Mx office. we have this very large document (indeed) because we have soo many updates and new features in Mx and we don't have any of this for our public. Is not just that we rewrite, we add a lot of missing and important information for our MX customers. The actual documentation is 30% useful and we really need this info updated, mostly because all the changes are based on the new legal requirement. 

So, we can cooperate to have this posted as soon as possible, Please tell us what we need to do in order to have this available for our customers :) we can handle any minor improvement after if you want, just consider that we have legal features released at least 8 months ago and we don't have any information about it. 

thank you so much for your help! cc: @samueljlieber @feav-odoo

**Comment by samueljlieber** [comment]
Hi @xpl-odoo! I corrected (per your CL/CO comments) as much as I could while maintaining the necessary content/images @feav-odoo and @lao-odoo described. The improvements here use considerably less images in place of descriptive text for instructions than what is in `mexico.rst` currently. I can certainly work with the team to improve this further in a second PR.

This is ready for your 👍 or 👎 - thank you 🙏

**Comment by feav-odoo** [comment]
Hello @xpl-odoo ! Do we have any updates with this? As our Product Owner, @lao-odoo , mentions, It's crucial for the Mexico Office, partners, customers, and the entire community to have the new guidelines of how l10n_mx works now. 

With a large percentage of the ~200 Monthly Mexico tickets we receive being something that this new documentation can quickly solve, these changes can do nothing but improve the quality of the module.

Have a good day!
cc @samueljlieber

**Comment by xpl-odoo** [comment]
> Hello @xpl-odoo ! Do we have any updates with this? As our Product Owner, @lao-odoo , mentions, It's crucial for the Mexico Office, partners, customers, and the entire community to have the new guidelines of how l10n_mx works now.
> 
> With a large percentage of the ~200 Monthly Mexico tickets we receive being something that this new documentation can quickly solve, these changes can do nothing but improve the quality of the module.
> 
> Have a good day! cc @samueljlieber

A lot could be improved, but @samueljlieber can already merge it and continue working on it afterward if it's urgent.
@robodoo delegate+

**Comment by samueljlieber** [comment]
Rebased to latest in https://github.com/odoo/documentation/commit/51898e00d651db448dcd5fffb054a5e514f6db10. Thank you @xpl-odoo, I will open another PR to improve this content after merge 🙂

@robodoo r+

**Pull request closed without merging**
