### PR TITLE
[IMP] accounting: add `name` to hashed fields

### PR DESCRIPTION
**Pull request by RicGR98**
This has been done in https://github.com/odoo/odoo/commit/1dcd071b27779e7d6d8f536c7dce7002d27212ba

### CODE REVIEW

**Review by dade-odoo — APPROVED** [review]
Thanks for the update @RicGR98 :raised_hands:

**Comment by RicGR98** [comment]
@robodoo up to saas-17.1

17.2+ done in: https://github.com/odoo/documentation/pull/8581

**Review by dade-odoo — APPROVED** [review]
Thanks for the addition!

**Comment by auva-odoo** [comment]
@robodoo r+ up to saas-17.1

**Pull request closed without merging**
