### PR TITLE
[MOV] MRP: Create subcontracting scope

### PR DESCRIPTION
**Pull request by hojo-odoo**
This PR creates a new subsection for subcontracting docs within the Manufacturing scope.

### CODE REVIEW

**Comment by hojo-odoo** [comment]
Hey @ksc-odoo,

This is ready for the first round of review.

Thanks,
hojo

**Review by ksc-odoo — APPROVED** [review]
Hey @hojo-odoo -- just finished my Peer Review. nice work on this [MOV] PR -- like the addition of the cards up top -- nice touch 👍 think this one is ready for the next stage whenever you're ready.

**Comment by hojo-odoo** [comment]
Hey @StraubCreative,

This is ready for final review.

Thanks,
hojo

**Review by StraubCreative — APPROVED** [review]
LGTM 👍 
Nice touch with the cards!

**Comment by StraubCreative** [comment]
@samueljlieber can you take a look?

**Review by samueljlieber — APPROVED** [review]
Looks good to me @hojo-odoo, nice job! 👍
...
@robodoo r+

**Pull request closed without merging**
