### PR TITLE
[IMP] accounting: update the information on recording payments

### PR DESCRIPTION
**Pull request by toaa-odoo**
I accidentally closed the previous branch (https://github.com/odoo/documentation/pull/2372)

### CODE REVIEW

**Comment by toaa-odoo** [comment]
@Donapi

**Review by jcs-odoo — COMMENTED** [review]
@Donapi some comments, but I'll force-push them myself.
I wonder if this isn't also valid for 14.0 but we can always backport if needed

**Comment by jcs-odoo** [comment]
Change line 36-38 from 15.0
```
   - If your main bank account is set as :doc:`oustanding account
     <../../bank/setup/outstanding_accounts>`, and the payment is made in Odoo (not related to a
     bank statement), invoices and bills are directly registered in the status :guilabel:`Paid`.

```

**Comment by jcs-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
