### PR TITLE
[IMP] POS: Remove vantiv integration

### PR DESCRIPTION
**Pull request by dikd-odoo**
[CANCELLED] Moved to PR

Removed Vantiv integration from 17.0 Sales POS documentation:

- Deleted Vantiv page from Point of Sale > Payment Methods > Terminals
- Updated Payment Terminals page content and image 

[Task](https://www.odoo.com/odoo/my-tasks/4077781?cids=3)

Target: 17.0+

### CODE REVIEW

**Comment by dikd-odoo** [comment]
Hi @jero-odoo, this PR is ready for a first-round review!

[Task](https://www.odoo.com/odoo/my-tasks/4077781?cids=3)

PS. Made these changes in 17.0 before I knew about forward port. I've made the same changes in a [separate PR for 15.0](https://github.com/odoo/documentation/pull/10429) and will request technical review +forward-port up to 16.4 for that PR once this 17.0 PR is approved :)

**Review by jero-odoo — APPROVED** [review]
Hi @dikd-odoo this update looks good! Approving to the next round!
One thing to note, the commit tag should be capitalized ([IMP] [ADD] [FIX], etc). You can use git commit --amend​ to change the commit tag :+1:

**Comment by dikd-odoo** [comment]
Thanks @jero-odoo, amended commit tag and noted for future PRs :)

**Comment by dikd-odoo** [comment]
Hello @odoo/us-doc-review @StraubCreative! This PR is ready for final review

**Comment by dikd-odoo** [comment]
Hello @samueljlieber, this PR is ready to review! 

Copying notes from its sibling #10429 for your reference:

We were assigned [a task](https://www.odoo.com/odoo/my-tasks/4077781) to remove Vantiv from our documentation as it is being deprecated from PoS terminals in 17.5. Because Vantiv is still currently available in 15.0-16.0, this PR is removing the vantiv.rst file and images but without the updated screenshot of available PoS terminals. 

The sibling PR #10426 is the update for 17.0+onward. I removed the vantiv.rst file and images and added an updated screenshot of available PoS terminals. 

Please let me know if you have any questions. Thank you!

**Pull request closed without merging**
