### PR TITLE
[ADD] accounting/l10n: new localization for luxembourg

### PR DESCRIPTION
**Pull request by jcs-odoo**
Do not forward-port immediately: content change in 14.0 and 15.0

task-id 2780977
https://www.odoo.com/web#id=2780977&menu_id=4720&cids=1&action=333&active_id=3835&model=project.task&view_type=form

### CODE REVIEW

**Comment by jcs-odoo** [comment]
content reviewed by Malika (mab)

**Review by AntoineVDV — APPROVED** [review]
@robodoo delegate+

**Comment by jcs-odoo** [comment]
@robodoo r+

**Comment by jcs-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
