### PR TITLE
[MOV] fleet: config doc to parent

### PR DESCRIPTION
**Pull request by larm-odoo**
Moving the content form the configuration doc to the main fleet doc. Deleting the old configuration doc. Updating all links throughout the doc, annd moving images to the correct location.

### CODE REVIEW

**Comment by larm-odoo** [comment]
Hi @samueljlieber  - this is ready for a tech review, per ZST.

**Review by samueljlieber — CHANGES_REQUESTED** [review]
Hi @larm-odoo, awesome job moving around the Fleet config content! This PR is just about perfect 😀, just missing a redirect rule for the `configuration.rst` file that was removed.

Please [add a redirect rule](https://github.com/odoo/documentation/blob/17.0/redirects/MANUAL.md) for this file in the `redirects/15.0.txt` file _after_ the `# applications/general` section:
```
# applications/hr

applications/hr/fleet/configuration.rst applications/hr/fleet.rst     # fleet/configuration -> fleet
```

Once this is addressed, tag me for another quick look! Thank you!

**Comment by samueljlieber** [comment]
> Redirect added, @samueljlieber ! Not sure how to test it after running make fast and looking at the doc- but I added it to the file. Should work!

@larm-odoo 
A good way to test a redirect is to `make html` (or `make fast`) and open the built documentation and navigate to your doc.

Then look at the URL: 
Screenshot 2024-04-04 at 2 49 26 PM

Next, take the _old_ file path (`applications/hr/fleet/configuration.rst`) and paste it into the URL of the built documentation, starting after `_build/html/` and be sure to change the file extension `.rst` to `.html`.

Screenshot 2024-04-04 at 2 50 12 PM

Upon hitting `Enter` you will be redirected to the _new_ file path that you added in the redirects file (`applications/hr/fleet.rst`).

**Comment by samueljlieber** [comment]
..
@robodoo r+

**Pull request closed without merging**
