### PR TITLE
[FIX] dev/assets: typo

### PR DESCRIPTION
**Pull request by kobros-tech**
the "py" letter should be "by" to make the syntax correct and understood.

### CODE REVIEW

**Review by ged-odoo — APPROVED** [review]

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by kobros-tech** [comment]
thanks @ged-odoo, there is still one for v17 same error and I made another pull for owl repo. regarding syntax error too.

**Review by Feyensv — APPROVED** [review]
@robodoo r+ squash

**Comment by kobros-tech** [comment]
Thanks @Feyensv for approval :)

**Pull request closed without merging**
