### PR TITLE
[IMP] *: Using class name corresponding to odoo models

### PR DESCRIPTION
**Pull request by Gorash**

### CODE REVIEW

**Review by kmagusiak — APPROVED** [review]

**Review by kmagusiak — APPROVED** [review]

**Review by AntoineVDV — APPROVED** [review]
@robodoo delegate+

**Review by rco-odoo — APPROVED** [review]

**Comment by rco-odoo** [comment]
@robodoo r+

**Comment by Gorash** [comment]
@robodoo rebase-ff r+

**Comment by Gorash** [comment]
@robodoo r+

**Pull request closed without merging**
