### PR TITLE
[IMP] developer/backend: correct filters attribute for calendar view fields

### PR DESCRIPTION
**Pull request by litnimax**

### CODE REVIEW

**Review by xmo-odoo — APPROVED** [review]

**Review by jcs-odoo — COMMENTED** [review]
Hello @xmo-odoo  :)
on this repository, don't forget to add odoo/doc-review as the next reviewer when you approve a pr on behalf of your codeowner team, otherwise, the PR remains at this stage.

I don't know if it is relevant or not, but this PR targets 15.0 (and above), although it is spelled "filter" and not "filters" in 13.0 and 14.0 as well. The file is in another path though --> `developer/reference/addons/views.rst`.
If you want to change the base of the branch and target of the PR, please switch this PR to draft first, so that it doesn't ping all codeowners. 

Thank you :)

**Comment by xmo-odoo** [comment]
> Hello @xmo-odoo :) on this repository, don't forget to add odoo/doc-review as the next reviewer when you approve a pr on behalf of your codeowner team, otherwise, the PR remains at this stage.
> 
> I don't know if it is relevant or not, but this PR targets 15.0 (and above), although it is spelled "filter" and not "filters" in 13.0 and 14.0 as well. The file is in another path though --> `developer/reference/addons/views.rst`. If you want to change the base of the branch and target of the PR, please switch this PR to draft first, so that it doesn't ping all codeowners.
> 
> Thank you :)

dogconfused

**Comment by jcs-odoo** [comment]
> > Hello @xmo-odoo :) on this repository, don't forget to add odoo/doc-review as the next reviewer when you approve a pr on behalf of your codeowner team, otherwise, the PR remains at this stage.
> > I don't know if it is relevant or not, but this PR targets 15.0 (and above), although it is spelled "filter" and not "filters" in 13.0 and 14.0 as well. The file is in another path though --> `developer/reference/addons/views.rst`. If you want to change the base of the branch and target of the PR, please switch this PR to draft first, so that it doesn't ping all codeowners.
> > Thank you :)
> 
> dogconfused

I've been laughing for a good 90 seconds

**Review by Feyensv — APPROVED** [review]
@robodoo r+ squash

**Pull request closed without merging**
