### PR TITLE
[ADD] payment providers: Xendit

### PR DESCRIPTION
**Pull request by nni-odoo**
taskid-2946329

### CODE REVIEW

**Review by toaa-odoo — APPROVED** [review]
Hi @nni-odoo, sorry for the delay. I'm not sure what the status of this task in RD is, but the documentation LGTM. I've made minor changes. I'm pinging @odoo/be-doc-review for the final review, but let us know if we have to give r+ rights should the task not be ready yet.

**Comment by nni-odoo** [comment]
Hi @toaa-odoo thank you for reviewing and making some change in it!
Actually, there is an ongoing PR https://github.com/odoo/odoo/pull/134255 in master here. I've made this PR to saas-16.3 here since there were some confusion into the target branch for this payment provider. I will create another documentation PR to master (with the same content) and tag you in it later on! 
I will keep this PR open first until the other one is ready

**Comment by toaa-odoo** [comment]
> Hi @toaa-odoo thank you for reviewing and making some change in it! Actually, there is an ongoing PR [odoo/odoo#134255](https://github.com/odoo/odoo/pull/134255) in master here. I've made this PR to saas-16.3 here since there were some confusion into the target branch for this payment provider. I will create another documentation PR to master (with the same content) and tag you in it later on! I will keep this PR open first until the other one is ready

Since the one in master is open, should this one be closed? @nni-odoo

**Comment by jcs-odoo** [comment]
> > Hi @toaa-odoo thank you for reviewing and making some change in it! Actually, there is an ongoing PR [odoo/odoo#134255](https://github.com/odoo/odoo/pull/134255) in master here. I've made this PR to saas-16.3 here since there were some confusion into the target branch for this payment provider. I will create another documentation PR to master (with the same content) and tag you in it later on! I will keep this PR open first until the other one is ready
> 
> Since the one in master #6045 is open, should this one be closed? @nni-odoo

**Pull request closed without merging**
