### PR TITLE
Cth odoo filter from

### PR DESCRIPTION
**Pull request by samueljlieber**
Follow up from #1449

> Odoo 15.0 introduced the ability to use a specific email server depending on the "From". So a new section "Set up different outgoing servers in a multi-company environment" has been added in the documentation. This explains the logic applied to select the right email server.

### CODE REVIEW

**Comment by samueljlieber** [comment]
This is a restoration of previous PR https://github.com/odoo/documentation/pull/1449 since the last forced update @ #1168ba6  failed.

The plan is to do a manual cherry-pick of the latest updates to `email_servers.rst` on a new PR because the commit history is messed up here. 

@cth-odoo @StraubCreative @tiku-odoo @AntoineVDV @std-odoo

**Comment by StraubCreative** [comment]
New cherry-pick up of this PR @ #2627.
Closing and moving over to new open PR.
@cth-odoo @tiku-odoo @AntoineVDV @std-odoo

**Comment by tiku-odoo** [comment]
@Abridbus @std-odoo When you have a moment can you review this change? I'm not sure we want to document using the from filter to achieve multi-company emailing. What are your thoughts? I had heard something from the R&D feedback project that multi-company emailing was in the works for future versions. We will be documenting the from_filter in as well: https://github.com/odoo/documentation/pull/2055 

We are open to suggestions. Thanks, Tim

**Comment by StraubCreative** [comment]
@tiku-odoo please take review over to #2627 this PR is closed ty :)

**Pull request closed without merging**
