### PR TITLE
[IMP] localizations: Philippines (SLSP and 2550Q)

### PR DESCRIPTION
**Pull request by ralo-odoo**
Added additonal sections for SLSP and 2550Q tax report as these were updated for 17.0 l10n_ph module

### CODE REVIEW

**Comment by toaa-odoo** [comment]
Hi @ralo-odoo! Replying because our team got automatically pinged. It seems you have a few build errors, if you want a review, you can ping us once they have been sorted out :)

**Comment by ralo-odoo** [comment]
Hi @toaa-odoo Thanks for the feedback! I have fixed the small formatting issues! Let me know if there is any further issues with the content!
Thanks!

**Review by toaa-odoo — CHANGES_REQUESTED** [review]
Hi @ralo-odoo ! Thanks for your great work. Unfortunately, I do not have the right to push myself on your fork, so instead I suggest you copy-paste the following text into the PR. It contains minor changes (such as commas, rephrasing of some sentences, formatting, etc.)

Two comments: 1) We usually go only one way of writing file format, that is either .xls (dot + small caps), or XLS (no dot + all caps). You can select whichever you prefer, but you have to be consistent throughout the page. I changed it for you in the C/C text :). 2) You currently have two commits, the bot will not know which ones has to be merged first, therefore you need to squash them first.

Cheers! :+1: 


===========
Philippines
===========

Configuration
=============

:ref:`Install <general/install>` the :guilabel:`🇵🇭 Philippines` :ref:`fiscal localization package
<fiscal_localizations/packages>` to get all the default accounting features of the Philippine
localization, such as a chart of accounts, taxes, and the BIR 2307 report. These provide a base
template to get started with using Philippine accounting.

.. note::
   - When creating a new database and selecting the `Philippines` as a country, the fiscal
     localization module **Philippines - Accounting** is automatically installed.
   - If the module is installed in an existing company, the **chart of accounts** and **taxes** will
     *not* be replaced if there are already posted journal entries.
   - The BIR 2307 report is installed, but the withholding taxes may need to be manually created.

Chart of accounts and taxes
---------------------------

A minimum configuration default chart of accounts is installed, and the following types of taxes are
installed and linked to the relevant account:

- Sales and Purchase VAT 12%
- Sales and Purchase VAT Exempt
- Sales and Purchase VAT Zero-Rated
- Purchase Withholding

For the withholding taxes (:menuselection:`Configuration --> Taxes`), there is an additional
:guilabel:`Philippines ATC` field under the :guilabel:`Philippines` tab.

.. image:: philippines/philippines-atc-code.png
   :alt: Philippines ATC code field set on taxes.

.. note::
   Taxes' ATC codes are used for the BIR 2307 report. If a tax is created manually, its ATC code
   must be added.

Contacts
--------

When a company or an individual (not belonging to a company) contact is located in the Philippines,
fill in the :guilabel:`Tax ID` field with their `Taxpayer Identification Number (TIN)`.

For individuals not belonging to a company, identify them by using the following additional fields:

- :guilabel:`First Name`
- :guilabel:`Middle Name`
- :guilabel:`Last Name`

.. image:: philippines/philippines-contact-individual.png
   :alt: Individual type contact with First, Middle, and Last Name fields.

.. note::
   For both :guilabel:`Company` and :guilabel:`Individual`, the TIN should follow the
   `NNN-NNN-NNN-NNNNN` format. The branch code should follow the last digits of the TIN, or else can
   be left as `00000`.

BIR 2307 report
===============

**BIR 2307** report data, also known as `Certificate of Creditable Tax Withheld at Source <https://www.bir.gov.ph/index.php/bir-forms/certificates.html>`_,
can be generated for purchase orders and vendor payments with the applicable withholding taxes.

To generate a BIR 2307 report, select one or multiple vendor bills from the list view, and click
:menuselection:`Action --> Download BIR 2307 XLS`.

.. image:: philippines/philippines-multi-bill.png
   :alt: Multiple vendor bills selected with action to "Download BIR 2307 XLS".

.. tip::
   The same action can be performed on a vendor bill from the form view.

A pop-up appears to review the selection, then click on :guilabel:`Generate`.

.. image:: philippines/philippines-generate.png
   :alt: Pop up menu to generate BIR 2307 XLS file.

This generates the `Form_2307.xls` file that lists all the vendor bill lines with the applicable
withholding tax.

The process above can also be used for a *single* vendor :doc:`payment <../accounting/payments>` if
it is linked to one or more :doc:`vendor bills <../accounting/payments>` with applied withholding
taxes.

.. note::
   - If there is no withholding tax applied, then the XLS file will not generate records for
     those vendor bill lines.
   - When grouping payments for multiple bills, Odoo splits the payments based on the contact.
     From a payment, clicking :menuselection:`Action --> Download BIR 2307 XLS` generates a report
     that only includes vendor bills related to that contact.

.. important::
   Odoo cannot generate the BIR 2307 PDF report or DAT files directly. The generated
   :file:`Form_2307.xls` file can be exported to an *external* tool to convert it to BIR DAT or PDF
   format.

SLSP Report
===========

The **SLSP** report also known as the *Summary List of Sales and Purchases* can be viewed and
exported (in XLSX format). The report can be viewed from
:menuselection:`Reporting --> Partner Reports --> Summary List of Sales and Purchases`.

The report is split into two sections which can be accessed from their respective buttons at the
top:

- :guilabel:`Sales` for :abbr:`SLS (Summary List of Sales)` report.
   All customer invoices with the associated sales taxes applied are shown on this report.
- :guilabel:`Purchases` for :abbr:`SLP (Summary List of Purchases)` report.
   All vendor bills with the associated purchase taxes applied care shown on this report.

.. image:: philippines/philippines-slsp.png
   :alt: SLSP Report

By default, both reports will exclude journal entries containing partners without a TIN number set
and those with importation taxes set. To view or hide them, the :guilabel:`Options:` button will
give additional filters to include these, among others:

- `Including Partners Without TIN`
- `Including Importations`

.. important::
   Odoo cannot generate the DAT files directly.
   The :guilabel:`Export SLSP` and :guilabel:`XLSX` buttons will export a XLSX file which can be
   processed using a *external* tool to convert it to the DAT format.

2550Q Tax report
================

The tax report report is viewed in
:menuselection:`Reporting --> Statement Reports --> Tax Report --> 2550Q(PH)`.
The form is based on the latest *2550Q (Quarterly Value-Added Tax Return)* Jan. 2023 version.

.. image:: philippines/philippines-2550Q.png
   :alt: 2550Q Tax Report

.. tip::
   Most lines in the tax report are automatically computed based on the taxes. For more accurate
   reporting and filing of the tax report, manual journal entries can also be mapped to the tax
   report through preconfigured **Tax Grids** for each tax report line.

.. important::
   Odoo cannot generate the 2550Q BIR formatted PDF report directly. It should be used as
   reference when externally filing the form manually or online.

**Comment by ralo-odoo** [comment]
@toaa-odoo Thanks for the feedback! Unfortunately, I think the way the code was pasted a lot of the rst formatting is gone as github applied those as markdown formatting so I couldn't directly copy paste it. I think either can re comment as code OR can do what we did before for the [other PR](https://github.com/odoo/documentation/pull/5187) where can create a new fork.
I ticked the "allow edits by maintainers option" so not sure if this helps with the access for you to commit directly on my fork.
image
Let me know your thoughts!

**Comment by toaa-odoo** [comment]
`===========
Philippines
===========

Configuration
=============

:ref:`Install <general/install>` the :guilabel:`🇵🇭 Philippines` :ref:`fiscal localization package
<fiscal_localizations/packages>` to get all the default accounting features of the Philippine
localization, such as a chart of accounts, taxes, and the BIR 2307 report. These provide a base
template to get started with using Philippine accounting.

.. note::
   - When creating a new database and selecting the `Philippines` as a country, the fiscal
     localization module **Philippines - Accounting** is automatically installed.
   - If the module is installed in an existing company, the **chart of accounts** and **taxes** will
     *not* be replaced if there are already posted journal entries.
   - The BIR 2307 report is installed, but the withholding taxes may need to be manually created.

Chart of accounts and taxes
---------------------------

A minimum configuration default chart of accounts is installed, and the following types of taxes are
installed and linked to the relevant account:

- Sales and Purchase VAT 12%
- Sales and Purchase VAT Exempt
- Sales and Purchase VAT Zero-Rated
- Purchase Withholding

For the withholding taxes (:menuselection:`Configuration --> Taxes`), there is an additional
:guilabel:`Philippines ATC` field under the :guilabel:`Philippines` tab.

.. image:: philippines/philippines-atc-code.png
   :alt: Philippines ATC code field set on taxes.

.. note::
   Taxes' ATC codes are used for the BIR 2307 report. If a tax is created manually, its ATC code
   must be added.

Contacts
--------

When a company or an individual (not belonging to a company) contact is located in the Philippines,
fill in the :guilabel:`Tax ID` field with their `Taxpayer Identification Number (TIN)`.

For individuals not belonging to a company, identify them by using the following additional fields:

- :guilabel:`First Name`
- :guilabel:`Middle Name`
- :guilabel:`Last Name`

.. image:: philippines/philippines-contact-individual.png
   :alt: Individual type contact with First, Middle, and Last Name fields.

.. note::
   For both :guilabel:`Company` and :guilabel:`Individual`, the TIN should follow the
   `NNN-NNN-NNN-NNNNN` format. The branch code should follow the last digits of the TIN, or else can
   be left as `00000`.

BIR 2307 report
===============

**BIR 2307** report data, also known as `Certificate of Creditable Tax Withheld at Source <https://www.bir.gov.ph/index.php/bir-forms/certificates.html>`_,
can be generated for purchase orders and vendor payments with the applicable withholding taxes.

To generate a BIR 2307 report, select one or multiple vendor bills from the list view, and click
:menuselection:`Action --> Download BIR 2307 XLS`.

.. image:: philippines/philippines-multi-bill.png
   :alt: Multiple vendor bills selected with action to "Download BIR 2307 XLS".

.. tip::
   The same action can be performed on a vendor bill from the form view.

A pop-up appears to review the selection, then click on :guilabel:`Generate`.

.. image:: philippines/philippines-generate.png
   :alt: Pop up menu to generate BIR 2307 XLS file.

This generates the `Form_2307.xls` file that lists all the vendor bill lines with the applicable
withholding tax.

The process above can also be used for a *single* vendor :doc:`payment <../accounting/payments>` if
it is linked to one or more :doc:`vendor bills <../accounting/payments>` with applied withholding
taxes.

.. note::
   - If there is no withholding tax applied, then the XLS file will not generate records for
     those vendor bill lines.
   - When grouping payments for multiple bills, Odoo splits the payments based on the contact.
     From a payment, clicking :menuselection:`Action --> Download BIR 2307 XLS` generates a report
     that only includes vendor bills related to that contact.

.. important::
   Odoo cannot generate the BIR 2307 PDF report or DAT files directly. The generated
   :file:`Form_2307.xls` file can be exported to an *external* tool to convert it to BIR DAT or PDF
   format.

SLSP Report
===========

The **SLSP** report also known as the *Summary List of Sales and Purchases* can be viewed and
exported (in XLSX format). The report can be viewed from
:menuselection:`Reporting --> Partner Reports --> Summary List of Sales and Purchases`.

The report is split into two sections which can be accessed from their respective buttons at the
top:

- :guilabel:`Sales` for :abbr:`SLS (Summary List of Sales)` report.
   All customer invoices with the associated sales taxes applied are shown on this report.
- :guilabel:`Purchases` for :abbr:`SLP (Summary List of Purchases)` report.
   All vendor bills with the associated purchase taxes applied care shown on this report.

.. image:: philippines/philippines-slsp.png
   :alt: SLSP Report

By default, both reports will exclude journal entries containing partners without a TIN number set
and those with importation taxes set. To view or hide them, the :guilabel:`Options:` button will
give additional filters to include these, among others:

- `Including Partners Without TIN`
- `Including Importations`

.. important::
   Odoo cannot generate the DAT files directly.
   The :guilabel:`Export SLSP` and :guilabel:`XLSX` buttons will export a XLSX file which can be
   processed using a *external* tool to convert it to the DAT format.

2550Q Tax report
================

The tax report report is viewed in
:menuselection:`Reporting --> Statement Reports --> Tax Report --> 2550Q(PH)`.
The form is based on the latest *2550Q (Quarterly Value-Added Tax Return)* Jan. 2023 version.

.. image:: philippines/philippines-2550Q.png
   :alt: 2550Q Tax Report

.. tip::
   Most lines in the tax report are automatically computed based on the taxes. For more accurate
   reporting and filing of the tax report, manual journal entries can also be mapped to the tax
   report through preconfigured **Tax Grids** for each tax report line.

.. important::
   Odoo cannot generate the 2550Q BIR formatted PDF report directly. It should be used as
   reference when externally filing the form manually or online.`

Test

**Comment by toaa-odoo** [comment]
```

===========
Philippines
===========

Configuration
=============

:ref:`Install <general/install>` the :guilabel:`🇵🇭 Philippines` :ref:`fiscal localization package
<fiscal_localizations/packages>` to get all the default accounting features of the Philippine
localization, such as a chart of accounts, taxes, and the BIR 2307 report. These provide a base
template to get started with using Philippine accounting.

.. note::
   - When creating a new database and selecting the `Philippines` as a country, the fiscal
     localization module **Philippines - Accounting** is automatically installed.
   - If the module is installed in an existing company, the **chart of accounts** and **taxes** will
     *not* be replaced if there are already posted journal entries.
   - The BIR 2307 report is installed, but the withholding taxes may need to be manually created.

Chart of accounts and taxes
---------------------------

A minimum configuration default chart of accounts is installed, and the following types of taxes are
installed and linked to the relevant account:

- Sales and Purchase VAT 12%
- Sales and Purchase VAT Exempt
- Sales and Purchase VAT Zero-Rated
- Purchase Withholding

For the withholding taxes (:menuselection:`Configuration --> Taxes`), there is an additional
:guilabel:`Philippines ATC` field under the :guilabel:`Philippines` tab.

.. image:: philippines/philippines-atc-code.png
   :alt: Philippines ATC code field set on taxes.

.. note::
   Taxes' ATC codes are used for the BIR 2307 report. If a tax is created manually, its ATC code
   must be added.

Contacts
--------

When a company or an individual (not belonging to a company) contact is located in the Philippines,
fill in the :guilabel:`Tax ID` field with their `Taxpayer Identification Number (TIN)`.

For individuals not belonging to a company, identify them by using the following additional fields:

- :guilabel:`First Name`
- :guilabel:`Middle Name`
- :guilabel:`Last Name`

.. image:: philippines/philippines-contact-individual.png
   :alt: Individual type contact with First, Middle, and Last Name fields.

.. note::
   For both :guilabel:`Company` and :guilabel:`Individual`, the TIN should follow the
   `NNN-NNN-NNN-NNNNN` format. The branch code should follow the last digits of the TIN, or else can
   be left as `00000`.

BIR 2307 report
===============

**BIR 2307** report data, also known as `Certificate of Creditable Tax Withheld at Source <https://www.bir.gov.ph/index.php/bir-forms/certificates.html>`_,
can be generated for purchase orders and vendor payments with the applicable withholding taxes.

To generate a BIR 2307 report, select one or multiple vendor bills from the list view, and click
:menuselection:`Action --> Download BIR 2307 XLS`.

.. image:: philippines/philippines-multi-bill.png
   :alt: Multiple vendor bills selected with action to "Download BIR 2307 XLS".

.. tip::
   The same action can be performed on a vendor bill from the form view.

A pop-up appears to review the selection, then click on :guilabel:`Generate`.

.. image:: philippines/philippines-generate.png
   :alt: Pop up menu to generate BIR 2307 XLS file.

This generates the `Form_2307.xls` file that lists all the vendor bill lines with the applicable
withholding tax.

The process above can also be used for a *single* vendor :doc:`payment <../accounting/payments>` if
it is linked to one or more :doc:`vendor bills <../accounting/payments>` with applied withholding
taxes.

.. note::
   - If there is no withholding tax applied, then the XLS file will not generate records for
     those vendor bill lines.
   - When grouping payments for multiple bills, Odoo splits the payments based on the contact.
     From a payment, clicking :menuselection:`Action --> Download BIR 2307 XLS` generates a report
     that only includes vendor bills related to that contact.

.. important::
   Odoo cannot generate the BIR 2307 PDF report or DAT files directly. The generated
   :file:`Form_2307.xls` file can be exported to an *external* tool to convert it to BIR DAT or PDF
   format.

SLSP Report
===========

The **SLSP** report also known as the *Summary List of Sales and Purchases* can be viewed and
exported (in XLSX format). The report can be viewed from
:menuselection:`Reporting --> Partner Reports --> Summary List of Sales and Purchases`.

The report is split into two sections which can be accessed from their respective buttons at the
top:

- :guilabel:`Sales` for :abbr:`SLS (Summary List of Sales)` report.
   All customer invoices with the associated sales taxes applied are shown on this report.
- :guilabel:`Purchases` for :abbr:`SLP (Summary List of Purchases)` report.
   All vendor bills with the associated purchase taxes applied care shown on this report.

.. image:: philippines/philippines-slsp.png
   :alt: SLSP Report

By default, both reports will exclude journal entries containing partners without a TIN number set
and those with importation taxes set. To view or hide them, the :guilabel:`Options:` button will
give additional filters to include these, among others:

- `Including Partners Without TIN`
- `Including Importations`

.. important::
   Odoo cannot generate the DAT files directly.
   The :guilabel:`Export SLSP` and :guilabel:`XLSX` buttons will export a XLSX file which can be
   processed using a *external* tool to convert it to the DAT format.

2550Q Tax report
================

The tax report report is viewed in
:menuselection:`Reporting --> Statement Reports --> Tax Report --> 2550Q(PH)`.
The form is based on the latest *2550Q (Quarterly Value-Added Tax Return)* Jan. 2023 version.

.. image:: philippines/philippines-2550Q.png
   :alt: 2550Q Tax Report

.. tip::
   Most lines in the tax report are automatically computed based on the taxes. For more accurate
   reporting and filing of the tax report, manual journal entries can also be mapped to the tax
   report through preconfigured **Tax Grids** for each tax report line.

.. important::
   Odoo cannot generate the 2550Q BIR formatted PDF report directly. It should be used as
   reference when externally filing the form manually or online.

```
My bad, you should now be able to c/p the text. The commits still need to be squashed as to only have one of them :)

**Comment by ralo-odoo** [comment]
@toaa-odoo thanks for that! I have made a new commit with your changes and tried to squash the commits but I am not sure if it worked as it now says there is 6 commits in the PR. Let me know if I should try again but apologies as I am not too familiar with git CLI commands.

**Comment by toaa-odoo** [comment]
> @toaa-odoo thanks for that! I have made a new commit with your changes and tried to squash the commits but I am not sure if it worked as it now says there is 6 commits in the PR. Let me know if I should try again but apologies as I am not too familiar with git CLI commands.

Hello, indeed the squash has not worked. I did the steps on locally on my machine (but since I cannot push on your branch, you will have to do them). It should go something like this:

1. Go on your branch and enter `git rebase 17.0 -i`
2. A list of commits will appear in a pop-up window, make sure to have the first (starting from the top) commit listed as "pick", and the others below as "squash"
3. Save and exit the window, you will now probably have conflicts
4. Click on the "commit" menu on the left (see screenshot), and click "Resolve" next to the philippines.rst file that should appear there. The right column is your newest changes, the middle one what it will look like when done resolving conflicts, and the left one the previous version before your commit.
5. You want to discard all changes from the left and include all the ones from the right
6. Save the changes when done
7. Then, enter `git add` and `git commit --amend`, save, and `git push --force-with-lease`

This should solve the issue, if you are having trouble let me know and I'll try to record a video for you :)

**Comment by ralo-odoo** [comment]
@toaa-odoo Thanks for your detailed explanation and steps! I encountered some issues along the way but I think I managed to rebase and squash then push! Let me know if there is any outstanding issues!

**Comment by toaa-odoo** [comment]
@ralo-odoo Hi, @jcs-odoo is fixing the aforementioned squash issues. He'll merge it when it's ready :)

**Comment by jcs-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
