### PR TITLE
[ADD] accounting: Incoterms

### PR DESCRIPTION
**Pull request by toaa-odoo**
Adding an Incoterms page to the documentation

taskid-3615863

### CODE REVIEW

**Comment by LoredanaLrpz** [comment]
since the incoterms page already exists in later versions (16 ->), does this page overwrites automatically that existing page? (@xpl-odoo )

**Comment by toaa-odoo** [comment]
> since the incoterms page already exists in later versions (16 ->), does this page overwrites automatically that existing page? (@xpl-odoo )

It shouldn't since this is only for 15.0, it's not to be forwarded beyond 15.2

**Review by LoredanaLrpz — APPROVED** [review]
I'm approving it, but I'd suggest referring to this doc on the intrastat doc as well. In later versions, it is referred to at the bottom of the page, but here you have a title "default incoterm" where this ref could fit.

**Comment by xpl-odoo** [comment]
@fw-bot up to 15.2

**Comment by xpl-odoo** [comment]
@fw-bot up to saas-15.2

**Review by xpl-odoo — APPROVED** [review]
@robodoo r+

**Comment by xpl-odoo** [comment]
@robodoo retry

**Pull request closed without merging**
