### PR TITLE
[IMP] accounting: clarfy mandatory field for EMV qr code

### PR DESCRIPTION
**Pull request by tong-odoo**

### CODE REVIEW

**Review by dade-odoo — APPROVED** [review]
Hi @tong-odoo - thanks for the clarification! Looks good to me :)

**Comment by dade-odoo** [comment]
@tong-odoo yes, sorry about that :) I've tagged @odoo/be-doc-review who can delegate r+ rights

**Review by auva-odoo — APPROVED** [review]
@robodoo delegate+

**Comment by tong-odoo** [comment]
@robodoo r+

**Pull request closed without merging**
