### PR TITLE
[REM] reference/user_interface: remove banner_route

### PR DESCRIPTION
**Pull request by aab-odoo**
This commit removes the documentation about the banner_route view attribute, which has been dropped in odoo/odoo#177244.

Task~4126004

### CODE REVIEW

**Review by AntoineVDV — APPROVED** [review]
@robodoo r+ delegate+

**Comment by Polymorphe57** [comment]
@robodoo r+

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
